### ISSUE TITLE
Rolling update of vmagent on Kubernetes fails when using hostPath mount

### ISSUE THREAD

**Issue by blesswinsamuel** [VictoriaMetrics/VictoriaMetrics#1146]
I'm running vmagent v1.51.0 on a single node kubernetes. I have configured vmagent to write temporary remote write data to local disk using `hostPath` mount. I didn't want to use `emptyDir`, as that would result in data loss during upgrade if there is a connectivity loss to remote write endpoint. 

Here is the relevant configuration 
```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - name: vmagent
          ...
          volumeMounts:
            - name: remote-write-data
              mountPath: /vmagent-remotewrite-data
      ...
      volumes:
        - name: remote-write-data
          hostPath:
            path: /path/on/host/file-system
            type: DirectoryOrCreate
```

When I make changes to the deployment configuration, during rolling update, the new pod panics (error log below) and it goes to CrashLoopBackOff as the first pod is already running and already has a lock on the filesystem.

```
2021-03-23T20:30:27.649Z	panic	VictoriaMetrics/lib/persistentqueue/persistentqueue.go:164	FATAL: cannot acquire lock on file "/vmagent-remotewrite-data/persistent-queue/1_E9FB4DF6D4FE4E87/flock.lock": resource temporarily unavailable
panic: FATAL: cannot acquire lock on file "/vmagent-remotewrite-data/persistent-queue/1_E9FB4DF6D4FE4E87/flock.lock": resource temporarily unavailable

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xa6a2cc, 0x5, 0xc0001763f0, 0x8f, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:258 +0xc25
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, 0xa6a2cc, 0x5, 0xa6dc0e, 0x9, 0xc0000bd660, 0x1, 0x1)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126 +0xd2
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:118
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:114
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.mustCreateFlockFile(0xc00002aa40, 0x3d, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:164 +0xc5
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.tryOpeningQueue(0xc00002aa40, 0x3d, 0xc000190940, 0xc, 0x20000080, 0x2000000, 0x1dcd6500, 0x0, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:201 +0x82d
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.mustOpen(0xc00002aa40, 0x3d, 0xc000190940, 0xc, 0x20000080, 0x2000000, 0x1dcd6500, 0xc2f6e0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:149 +0x171
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.MustOpen(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:139
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.MustOpenFastQueue(0xc00002aa40, 0x3d, 0xc000190940, 0xc, 0xc8, 0x1dcd6500, 0x3d)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/fastqueue.go:43 +0x94
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newRemoteWriteCtx(0x0, 0x7ffc3de5b6d5, 0x81, 0xc8, 0xc000190940, 0xc, 0xc)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:211 +0x1c9
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.Init()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:93 +0x2bc
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/main.go:90 +0x2e5
```

Any recommendations on how to solve this?

One option I tried is to use the deployment strategy `Recreate` - it works, but I'm open to any better solutions, if any.

Now, I want to run vmagent using victoriametrics operator to be able to discover other services using `ServiceMonitor` CRD. In operator, I see that the deployment strategy is [hardcoded to Rolling](https://github.com/VictoriaMetrics/operator/blob/80ffc7dc5bbf5e883362f3976c759fd460a380db/controllers/factory/vmagent.go#L256-L259) and no way to configure it. Any suggestions on how to solve this use case would be helpful. Thanks.

**Comment by f41gh7** [comment]
`Recreate` seems to be only one relevant solution for your case. Its possible to add `updateStrategy` option to `VMAgent` `CRD`, will do it at next release.

 Other possible solution to use Statefulset with VolumeClaimTemplate, operator will support it soon as well.

**Comment by blesswinsamuel** [comment]
@f41gh7 Thank you for your quick response and adding this option so quickly! 
I tested the new operator version `0.12.1`. `updateStrategy: Recreate` works well.. Feel free to close this issue.
