### ISSUE TITLE
Frequent error in vmstorage

### ISSUE THREAD

**Issue by sudhir-maurya** [VictoriaMetrics/VictoriaMetrics#1216]
Hi, I have a cluster setup of 2 instances each with the remote storage as NFS. we have given all sorts of permission to the NFS directory where data is getting stored. Every once in 2 or 3 days I am getting the error. 
I would like to understand if there is any permanent solution for below error scenarios.

Pasting different log scenarios below:

First Error log scenario

```
2021-04-13T04:16:23.684Z        panic   VictoriaMetrics/lib/mergeset/table.go:570       FATAL: cannot merge raw parts: cannot write metadata to destination part "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0": cannot create "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0/metadata.json": cannot move "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0/metadata.json.tmp.10971" to "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0/metadata.json": rename /VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0/metadata.json.tmp.10971 /VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/16752A59A3E8C7B0/metadata.json: 
2021-04-13T21:33:38.645Z        info    VictoriaMetrics/lib/storage/partition.go:1257   merged 52508 rows across 50229 blocks in 16.463 seconds at 3189 rows/sec to "/VmstoreData/prometheus1/data/small/2021_04/48891_46612_20210413213253.991_20210413213316.524_1675773CF8FFA630"; sizeBytes: 363426
2021-04-13T21:33:49.033Z        panic   VictoriaMetrics/lib/mergeset/table.go:676       FATAL: unrecoverable error when merging parts in "/VmstoreData/prometheus1/indexdb/167334651C6896DB": cannot write metadata to destination part "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3": cannot create "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json": cannot create file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489": cannot create file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489": open /VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489: permission denied
2021-04-13T21:33:49.034Z        panic   VictoriaMetrics/lib/fs/reader_at.go:92  FATAL: cannot open file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/202_1_1675770250B740C2/lens.bin" for reading: open /VmstoreData/prometheus1/indexdb/167334651C6896DB/202_1_1675770250B740C2/lens.bin: permission denied

```

Second Error Log scenario

```
panic: FATAL: unrecoverable error when merging parts in "/VmstoreData/prometheus1/indexdb/167334651C6896DB": cannot write metadata to destination part "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3": cannot create "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json": cannot create file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489": cannot create file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489": open /VmstoreData/prometheus1/indexdb/167334651C6896DB/tmp/1675770250B740C3/metadata.json.tmp.4489: permission denied
goroutine 63 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0x9b746a, 0x5, 0xc00e4d62c0, 0x2a3, 0x4)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:272 +0xc69
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, 0x9b746a, 0x5, 0x9d13bc, 0x37, 0xc03b1e9fa8, 0x2, 0x2)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:140 +0xd1
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:132
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:128
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers.func1(0xc000542000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:676 +0x12b
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:674 +0x69
panic: FATAL: cannot open file "/VmstoreData/prometheus1/indexdb/167334651C6896DB/202_1_1675770250B740C2/lens.bin" for reading: open /VmstoreData/prometheus1/indexdb/167334651C6896DB/202_1_1675770250B740C2/lens.bin: permission denied

goroutine 91 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0x9b746a, 0x5, 0xc007e2d950, 0xe4, 0x4)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:272 +0xc69
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, 0x9b746a, 0x5, 0x9ca97e, 0x2a, 0xc0089517b8, 0x2, 0x2)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:140 +0xd1
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:132
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:128
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustOpenReaderAt(0xc0403a1860, 0x52, 0x49)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go:92 +0x45f
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.openFilePart(0xc045aa0370, 0x49, 0x32, 0xc045aa03c0, 0x47)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go:90 +0x4b8
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc000542000, 0xc00221ed08, 0x1, 0x1, 0x0, 0xc008951f01, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:857 +0xf53
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeRawItemsBlocks(0xc000542000, 0xc008862c40, 0x1, 0x1)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:569 +0x5b6
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).flushRawItems(0xc000542000, 0xc008951f00)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:546 +0x12a
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).rawItemsFlusher(0xc000542000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:430 +0x85
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startRawItemsFlusher.func1(0xc000542000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:417 +0x2b
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startRawItemsFlusher
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:416 +0x5f 
```

**Comment by f41gh7** [comment]
Hello, is it possible, that someone changes permission for this folder? Also, check mount permissions http://nfs.sourceforge.net/nfs-howto/ar01s07.html#pemission_issues

**Comment by sudhir-maurya** [comment]
Thanks a lot @f41gh7 for prompt response. Issue seems to be with NSF storage type. works fine when moved to ext4 File system. 
closing now.
