### ISSUE TITLE
Panic on rollup_result_cache

### ISSUE THREAD

**Issue by gnulux** [VictoriaMetrics/VictoriaMetrics#1939]
**Describe the bug**
I have this bug message and my container restarted 2 times today . 
How can i fix this

**To Reproduce**
don't know

**Expected behavior**

**Logs**
```
2021-12-13T14:00:30.688Z	panic	VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:417	BUG: unexpected values after merging new values; got 192; want 97
panic: BUG: unexpected values after merging new values; got 192; want 97
goroutine 3130 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xac07e2, 0x40}, {0xc0023fce60, 0x41}, 0x2)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:270 +0x994
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xac07e2, 0xc001828aa0}, {0xaee59b, 0xc0029c7760}, {0xc0029c7860, 0x7fbaf9e23f18, 0xc0001b033f})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.mergeTimeseries({0xc005848370, 0x1, 0xc0009c0bd0}, {0xc0058483a0, 0xacad79, 0x1}, 0x17db3fc5bc0, 0xc005852460)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:417 +0x76d
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFuncWithMetricExpr(0xc005852460, {0xc000c08600, 0xd2b620}, 0xa38520, {0xd2b600, 0xc0009c0cf0}, 0xc0009c0bd0, 0x0, 0x32a0d0a72052a5)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:699 +0xa77
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFunc(0xc005852460, {0xc000c08600, 0xc000c08600}, 0x10, {0xd2b600, 0xc0009c0cf0}, 0xc004ea11d0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:509 +0x457
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0xc005852460, {0xd2b600, 0xc0009c0cf0})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:234 +0xbe5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:290 +0x149
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:287 +0x373
```

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20211202-133618-tags-v1.70.0-0-g7f2f26b25
```

**VictoriaMetrics monitoring screenshots**
 
![victoria3](https://user-images.githubusercontent.com/5651212/145829330-f98d9b45-66d3-4b8e-9932-72ee4cab1668.png)
![victoria2](https://user-images.githubusercontent.com/5651212/145829333-942ac87d-41d7-440b-99fa-830fd86b6350.png)
![victoria1](https://user-images.githubusercontent.com/5651212/145829337-d08c7089-f67e-4cc0-b599-99d2921788e4.png)

**Comment by YuriKravetc** [comment]
Hi,

Were there any changes to your configuration\setup preceding this issue?
Can you attach the resource usage graphs please? (cpu\ram)

**Comment by gnulux** [comment]
Hi,

No change made , i had the same error with v1.69 so i updated  to V1.70  as you can see with the same behaviour
This instance is used to store metrics coming from telegraf 
My config  starts as a container like this : 
```
containers:
  - args:
    - -storageDataPath=/storage
    - -retentionPeriod=12
    - -httpListenAddr=:8428
    - -opentsdbHTTPListenAddr=:4242
    - -selfScrapeInterval=10s
    - -memory.allowedBytes=500MB
    - -promscrape.config=/config/scrape_config.yaml
    command:
    - /victoria-metrics-prod
 ```
![victoria4](https://user-images.githubusercontent.com/5651212/145962891-6c992293-876e-479c-861a-3098cf2b8cc9.png)

**Comment by YuriKravetc** [comment]
The most possible reason for receiving such an error is an incorrect shut down of VM.

Please try doing the following:
1) Try to stop VictoriaMetrics by sending `SIGINT ` signal.
2) Go to `storageDataPath` that you have indicated and remove the cache folder there.
3) Start VM again and test to see if a similar error will appear.

Best regards,

**Comment by gnulux** [comment]
I did that already by creating a file in folder /storage/cache/reset_cache_on_startup then restart VM . 
I think it's the same. is it ? 
VM does not restart since yesterday , i'm still keeping one eye on it .

**Comment by valyala** [comment]
@gnulux , could you check whether the issue still persists in [VictoriaMetrics v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the problem still exists.
