### ISSUE TITLE
"cannot allocate memory" error and panic on query

### ISSUE THREAD

**Issue by turbotankist** [VictoriaMetrics/VictoriaMetrics#195]
we have dashboard with k8s metrics - cpu and memory usage of pods.
sometimes if we take graphs of last 12h victoriametrics fails with error
```
2019-09-30T08:20:19.131+0000	panic	VictoriaMetrics@/lib/fs/fs.go:38	FATAL: cannot read 32 bytes at offset 12077988 of file "/storage/indexdb/15B62223C0874F23/60239141_78955_15C854294B2FE8E3/lens.bin": read /storage/indexdb/15B62223C0874F23/60239141_78955_15C854294B2FE8E3/lens.bin: cannot allocate memory
2019-09-30T08:20:19.131+0000	panic	VictoriaMetrics@/lib/storage/table_search.go:175	BUG: missing Init call before MustClose call
2019-09-30T08:20:19.132+0000	error	net/http/server.go:3053	http: panic serving 10.100.66.5:52538: BUG: missing Init call before MustClose call
goroutine 43535 [running]:
net/http.(*conn).serve.func1(0xc001c60000)
	net/http/server.go:1767 +0x139
panic(0xa4f3e0, 0xc0202a56f0)
	runtime/panic.go:679 +0x1b2
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xaeacd5, 0x5, 0xc0051bc300, 0x2c, 0x3)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:124 +0x586
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(0xaeacd5, 0x5, 0xb058f3, 0x2c, 0x0, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:78 +0x112
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:62
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*tableSearch).MustClose(0xc0054aee68)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/table_search.go:175 +0xfe
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Search).MustClose(0xc0054aee40)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/search.go:141 +0x3c
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.putStorageSearch(0xc0054aee40)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/netstorage/netstorage.go:457 +0x3e
panic(0xa4f3e0, 0xc0202a5690)
	runtime/panic.go:679 +0x1b2
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xaeacd5, 0x5, 0xc00c726690, 0xec, 0x3)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:124 +0x586
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(0xaeacd5, 0x5, 0xb0c325, 0x37, 0xc003f862d8, 0x4, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:78 +0x112
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:62
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.(*ReaderAt).ReadAt(0xc0000f0138, 0xc00521a240, 0x20, 0x240, 0xb84ba4)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/fs/fs.go:38 +0x2f1
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).readInmemoryBlock(0xc007f87500, 0xc003adf7f0, 0x0, 0xbdfb694, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/part_search.go:348 +0x215
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).getInmemoryBlock(0xc007f87500, 0xc003adf7f0, 0x2, 0x1, 0x0, 0xc003f864c0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/part_search.go:333 +0xa1
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).nextBlock(0xc007f87500, 0x8, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/part_search.go:262 +0x99
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).NextItem(0xc007f87500, 0xc005072478)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/part_search.go:230 +0x9e
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*TableSearch).nextBlock(0xc005072428, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table_search.go:161 +0x48
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*TableSearch).NextItem(0xc005072428, 0xc0154eb3b0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table_search.go:149 +0x44
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getMetricIDsForDate(0xc005072420, 0x46f2, 0xc0154eb3b0, 0x17d78415, 0x0, 0x6619020000000000)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1925 +0x484
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getMetricIDsForTimeRange(0xc005072420, 0x16d5d1dd820, 0x16d820aaa00, 0x17d78415, 0x0, 0xbacc20, 0xc000056f90)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1820 +0x163
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getTagFilterWithMinMetricIDsCountOptimized(0xc005072420, 0xc0155e2270, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d01, 0xc01569ce96, 0x11, 0xc015558e73, 0x11)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1263 +0x16d
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).updateMetricIDsForTagFilters(0xc005072420, 0xc003f86950, 0xc0155e2270, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d01, 0xc007f87500, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1540 +0xee
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).searchMetricIDs(0xc005072420, 0xc01f0e6288, 0x1, 0x1, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d00, 0xa, 0xb, 0x0, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1507 +0x14c
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).searchTSIDs(0xc005072420, 0xc01f0e6288, 0x1, 0x1, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d00, 0xc00a29d100, 0x5a, 0x80, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:1117 +0x1c7
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).searchTSIDs(0xc002ab09c0, 0xc01f0e6288, 0x1, 0x1, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d00, 0x0, 0x0, 0x0, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/index_db.go:975 +0x217
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).searchTSIDs(0xc000182000, 0xc01f0e6288, 0x1, 0x1, 0x16d5d1dd820, 0x16d820aaa00, 0x1312d00, 0xf5a080, 0xc0013b8d70, 0x40e7c8, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/storage.go:586 +0xcd
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Search).Init(0xc0054aee40, 0xc000182000, 0xc01f0e6288, 0x1, 0x1, 0x16d5d1dd820, 0x16d820aaa00, 0x1, 0x1312d00)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/search.go:121 +0xad
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.ProcessSearchQuery(0xc0013b9298, 0xc0188d9401, 0xbf5c8c974c5ad568, 0x28324cb65d, 0xf5b1a0, 0x6fc23ac00, 0x0, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/netstorage/netstorage.go:482 +0x1fc
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFuncWithMetricExpr(0xc0038b0b60, 0xaf10b1, 0xe, 0xb1aba0, 0xc0155e2120, 0xc0188d9460, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/promql/eval.go:575 +0x212
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFunc(0xc0038b0b60, 0xaf10b1, 0xe, 0xb1aba0, 0xc00ce1d630, 0xc0188d9460, 0x0, 0x0, 0x1, 0x1, ...)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/promql/eval.go:410 +0x435
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0xc0038b0b60, 0xbacc80, 0xc00ce1d590, 0xc00ce1d590, 0x0, 0x0, 0x68, 0xc0038b0b60)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/promql/eval.go:212 +0xd09
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.Exec(0xc0038b0b60, 0xc00a7b8de0, 0x55, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/promql/exec.go:58 +0xdf
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.QueryRangeHandler(0xbb6940, 0xc0130bbf80, 0xc003966400, 0x1, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/prometheus/prometheus.go:571 +0x3b9
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect.RequestHandler(0xbb6940, 0xc0130bbf80, 0xc003966400, 0xc0005cfb00)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/vmselect/main.go:112 +0x9ac
main.requestHandler(0xbb6940, 0xc0130bbf80, 0xc003966400, 0xc0130bbf00)
	github.com/VictoriaMetrics/VictoriaMetrics@/app/victoria-metrics/main.go:56 +0x6c
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xbb6940, 0xc0130bbf80, 0xc003966400, 0xb1b1a0)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/httpserver/httpserver.go:185 +0x1c3
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1(0xbb6940, 0xc0130bbf80, 0xc003966400)
	github.com/VictoriaMetrics/VictoriaMetrics@/lib/httpserver/httpserver.go:144 +0x88
net/http.HandlerFunc.ServeHTTP(0xc000170540, 0xbb6d40, 0xc003f7a000, 0xc003966400)
	net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000cd2000, 0xbb6d40, 0xc003f7a000, 0xc003966400)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc001c60000, 0xbb8840, 0xc015b8fc80)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2927 +0x38e
```
but sometimes it can show last 7 days without any problems.

**Comment by hagen1778** [comment]
Hi @turbotankist !
Error message `cannot allocate memory` returned by OS and means there are no available RAM to allocate data while reading from disk. Is it possible for you to increase memory size for installation?
It would be great if you share your current resource limitations and query you running. 
You may also want to investigate similar issues about memory - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/189

**Comment by turbotankist** [comment]
> Hi @turbotankist !
> Error message `cannot allocate memory` returned by OS and means there are no available RAM to allocate data while reading from disk. Is it possible for you to increase memory size for installation?
> It would be great if you share your current resource limitations and query you running.
> You may also want to investigate similar issue about memory - #189

We have node with 15G memory only for  fvictoriametrics 

```
          resources:
            limits:
              cpu: 3700m
              memory: 14024Mi
```
but on time of crash VM used only about 5GB

**Comment by valyala** [comment]
Probably heavy query hit VM during this time, the query instantly allocated more than 10GB of remaining RAM and this led to OOM.

**Comment by valyala** [comment]
@turbotankist , try upgrading to [v1.28.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It should use lower amounts of RAM on heavy queries comparing to the previous release.

**Comment by turbotankist** [comment]
Yes, v1.28.0 much better. 
thanks
