### ISSUE TITLE
vmagent error

### ISSUE THREAD

**Issue by symmetriac** [VictoriaMetrics/VictoriaMetrics#1981]
vmagent crashes with error

```
          VictoriaMetrics/lib/promscrape/scraper.go:367\tec2_sd_configs:
          added targets: 243, removed targets: 0; total targets: 243
2021-12-18T16:36:43.456Z\tpanic\tVictoriaMetrics/lib/persistentqueue/persistentqueue.go:464\tBUG:
          readerOffset=64682 cannot exceed writerOffset=60738
panic: BUG: readerOffset=64682 cannot exceed writerOffset=60738

goroutine 35 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xad3342,
          0x5, 0xc004168240, 0x38, 0x4)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:270
          +0xc69
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1,
          0xad3342, 0x5, 0xaf06e2, 0x32, 0xc000293620, 0x2, 0x2)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138
          +0xd1
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.(*queue).MustReadBlockNonblocking(0xc0000c8270,
          0x0, 0x0, 0x0, 0x70, 0xc0000d8380, 0x9, 0x1)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/persistentqueue.go:464
          +0x33c
github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.(*FastQueue).MustReadBlock(0xc0001e0000,
          0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue/fastqueue.go:187
          +0x205
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*client).runWorker(0xc0000c8dd0)
  github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/client.go:204
          +0xa5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newClient.func1(0xc0000c8dd0)
  github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/client.go:142
          +0x57
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newClient
  github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/client.go:140
          +0xa0d
```

**Version**
```/ # /vmagent-prod --version
vmagent-20210819-092258-tags-v1.64.1-0-ga724229b5
```

**Used command-line flags**
``` 
flag{name="httpListenAddr", value=":8429", is_set="true"} 1
flag{name="promscrape.config", value="/etc/vmagent/config_out/vmagent.env.yaml", is_set="true"} 1
flag{name="remoteWrite.maxDiskUsagePerURL", value="1073741824", is_set="true"} 1
flag{name="remoteWrite.tmpDataPath", value="/tmp/vmagent-remotewrite-data", is_set="true"} 1
flag{name="remoteWrite.url", value="secret", is_set="true"} 1
```

**Comment by valyala** [comment]
This panic could occur after unclean shutdown of `vmagent`, e.g. when `vmagent` wasn't shut down with `SIGINT` signal (for example after out of memory crash or after terminating `vmagent` process with `kill -9`). In this case `vmagent` could leave files with pending data, which must be written to the configured `-remoteWrite.url` systems, in inconsistent state. The given panic could occur on the next start of `vmagent`. The temporary solution is to restart `vmagent` again - it should automatically detect the corrupted files with pending data and remove it. Another solution - is to delete the corrupted files manually. Just stop `vmagent` and then remove all the contents of the directory pointed by `-remoteWrite.tmpDataPath` command-line flag. By default this flag points to `vmagent-remotewrite-data` directory. See `./vmagent -help` output for this flag below:

```
  -remoteWrite.tmpDataPath string
        Path to directory where temporary data for remote write component is stored. See also -remoteWrite.maxDiskUsagePerURL (default "vmagent-remotewrite-data")
```

**Comment by valyala** [comment]
Closing this question as answered.
