### ISSUE TITLE
VMSelect panic

### ISSUE THREAD

**Issue by Jchicode** [VictoriaMetrics/VictoriaMetrics#2052]
Describe the bug

Hi,MSELECT panics frequently, I don't know if it is because my version is too low or some settings are wrong.
The size of the cache setting is 8Gb.

```2022-01-11T02:18:26.543359849Z 2022-01-11T02:18:26.543Z	panic	VictoriaMetrics/lib/fs/reader_at.go:100	FATAL: error in fstat("/cache/tmp/searchResults/065747397"): stat /cache/tmp/searchResults/065747397: input/output error
2022-01-11T02:18:26.548258231Z panic: FATAL: error in fstat("/cache/tmp/searchResults/065747397"): stat /cache/tmp/searchResults/065747397: input/output error
2022-01-11T02:18:26.548378132Z 
2022-01-11T02:18:26.550699108Z goroutine 58339 [running]:
2022-01-11T02:18:26.551685563Z github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0x9fbb07, 0x5, 0xc009a31100, 0x78, 0x4)
2022-01-11T02:18:26.551935028Z 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:270 +0xc69
2022-01-11T02:18:26.553869862Z github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, 0x9fbb07, 0x5, 0xa0624b, 0x1d, 0xc00264a7b0, 0x2, 0x2)
2022-01-11T02:18:26.553886465Z 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0xd1
2022-01-11T02:18:26.553893512Z github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
2022-01-11T02:18:26.553899618Z 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
2022-01-11T02:18:26.553905610Z github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
2022-01-11T02:18:26.553911621Z 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
2022-01-11T02:18:26.553917531Z github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustOpenReaderAt(0xc0087c7cb0, 0x22, 0x410c8)
2022-01-11T02:18:26.553923620Z 	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go:100 +0x36d
2022-01-11T02:18:26.553929610Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*tmpBlocksFile).Finalize(0xc0791ddad0, 0xc059784300, 0xc00264ab98)
2022-01-11T02:18:26.553935786Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:136 +0x1bd
2022-01-11T02:18:26.554400843Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.ProcessSearchQuery(0xc0083b3638, 0xc117902500, 0xc00264ab98, 0x1, 0x61dce92e, 0xdf8475800, 0xa037c9, 0x18, 0x493e0, 0x0, ...)
2022-01-11T02:18:26.554720137Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1323 +0x31a
2022-01-11T02:18:26.555361999Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFuncWithMetricExpr(0xc0003768f0, 0xc00993431f, 0x5, 0xa8af40, 0xaee660, 0xc060a59c20, 0xc001ee68a0, 0xc0083d7cc0, 0xc00993437c, 0x2, ...)
2022-01-11T02:18:26.555379907Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:719 +0x43f
2022-01-11T02:18:26.555386102Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFunc(0xc0003768f0, 0xc00993431f, 0x5, 0xa8af40, 0xaee660, 0xc060a59c20, 0xc000d225a0, 0xc0083d7cc0, 0xa8b370, 0xc000030e20, ...)
2022-01-11T02:18:26.555392091Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:520 +0x4d0
2022-01-11T02:18:26.555397333Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0xc0003768f0, 0xaee660, 0xc060a59c20, 0xc00f67af30, 0xc0021f3cc0, 0xc00b07a6e0, 0xc01a5518e0, 0xaee9c0)
2022-01-11T02:18:26.555403262Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:269 +0xdec
2022-01-11T02:18:26.555408675Z github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr.func1(0xc0083b3680, 0xc000376790, 0xc003e5aea0, 0xc0083b3670, 0xc01a551990, 0xc00842d6b0)
2022-01-11T02:18:26.555414226Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:304 +0x14c
2022-01-11T02:18:26.555419609Z created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr
2022-01-11T02:18:26.555425086Z 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:301 +0x3d2
```

Version
v1.61.0-cluster

**Comment by hagen1778** [comment]
Hi! Which filesystem is used for `/cache/tmp` folder?
The error "input/output error" is returned by operating system. It usually indicates the impossibility to read/write a file and the most likely causes of this error are disk defects, insufficient permissions or file corruption by other processes. Please, ensure that file exists, there are no disk errors and vmselect is the only process who has access to modify those files.

**Comment by Jchicode** [comment]
> Hi! Which filesystem is used for `/cache/tmp` folder? The error "input/output error" is returned by operating system. It usually indicates the impossibility to read/write a file and the most likely causes of this error are disk defects, insufficient permissions or file corruption by other processes. Please, ensure that file exists, there are no disk errors and vmselect is the only process who has access to modify those files.

Hi,```/cache``` mounts an NFS type PVC in kubernetes.
VMSelect will also explode this error：
```
panic: FATAL: cannot remove "/cache/tmp/searchResults/563616294": remove /cache/tmp/searchResults/563616294: no such file or directory
```
Before, there was not much data and it ran normally. Recently, there have been many slow queries in the log, which caused the panic to appear.
My VMSelect launches three pods with a resource limit of 2 cores 8GB.
```/cache/tmp``` directory still has free disk.

**Comment by Jchicode** [comment]
Hi! 
Before panic, VMSelect memory will suddenly rise close to the resource limit,  ```-memory.allowedBytes```is set  4GB.

**Comment by hagen1778** [comment]
I see. Looks like a network/NFS related issue. Not sure if anything can be done from the VM side.
Is it possible to verify if the mentioned in error file or folder actually exist and are reachable? Any chance to avoid using NFS for caching directories (I don't see much sense in this, since it is very important for cache to be fast for access).

**Comment by Jchicode** [comment]
Thank you!
Now I set the cachepath to be empty, and I haven't found any problems when running.
But in VMAuth, there are intermittent context problems. The content of the error is as follows.
```
2022-01-12T14:08:09.274Z	error	/usr/local/go/src/net/http/httputil/reverseproxy.go:488	http: proxy error: context canceled
2022-01-12T14:08:09.274Z	error	/usr/local/go/src/net/http/httputil/reverseproxy.go:488	http: proxy error: context canceled
2022-01-12T14:08:09.274Z	error	/usr/local/go/src/net/http/httputil/reverseproxy.go:488	http: proxy error: context canceled
2022-01-12T14:08:09.274Z	error	/usr/local/go/src/net/http/httputil/reverseproxy.go:488	http: proxy error: context canceled
2022-01-12T14:08:09.274Z	error	/usr/local/go/src/net/http/httputil/reverseproxy.go:488	http: proxy error: context canceled

```
my request is
```
http://victoria-metrics-vmauth:8427/write?consistency=&db=msp&precision=ms&rp=
```
VMInsert write monitoring on error
![798b80e94265693d6715c44dd6bd2bc](https://user-images.githubusercontent.com/12872991/149170145-6c18dd82-e60d-4717-ac43-40f16697df74.png)

VMInsert configuration
![image](https://user-images.githubusercontent.com/12872991/149170218-6cfd71b5-91de-49fe-a4b0-26115b7a1a1d.png)

**Comment by hagen1778** [comment]
The error "context canceled" means client cancelled the proxied request, so proxy (vmauth) cancels it as well.
For example, you can observe this error on the moment when you shutdown vminsert and it interrupts all the active connections.
Also, I'm not sure if these cancelled requests are actually from vminsert - it could be anything. Please, check `rate(vm_http_requests_total{job="vmauth-job"})` to see which HTTP handlers were incremented in that moment.

**Comment by Jchicode** [comment]
Hi！
Sorry, my VMSelect, VMInsert, and VMAuth are deployed on the same node. The VMSelect memory is full of the rest of the node, causing VMAuth to temporarily sleep. 
Maybe this is the reason for the "context canceled" error.
Now I schedule VMSelect to other nodes and it runs without errors.

**Comment by Jchicode** [comment]
About VMSelect ```/cache/tmp``` panic error, I will try other file systems next.

**Comment by Jchicode** [comment]
Thank you! @hagen1778
