### ISSUE TITLE
Unexpected power outage timestamps.bin: no such file or directory

### ISSUE THREAD

**Issue by marksugar** [VictoriaMetrics/VictoriaMetrics#2616]
[1414](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1414)
[1328](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1328)

my VictoriaMetrics version v1.76.1

```
-19T08:02:27.123Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: victoria-metrics-20220412-134346-tags-v1.76.1-0-gf8de318bf
2022-05-19T08:02:27.123Z        info    VictoriaMetrics/lib/logger/flag.go:13   command line flags
2022-05-19T08:02:27.123Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "retentionPeriod"="1w"
2022-05-19T08:02:27.123Z        info    VictoriaMetrics/lib/logger/flag.go:20   flag "storageDataPath"="/var/lib/victoria-metrics-data"
2022-05-19T08:02:27.123Z        info    VictoriaMetrics/app/victoria-metrics/main.go:52 starting VictoriaMetrics at ":8428"...
2022-05-19T08:02:27.123Z        info    VictoriaMetrics/app/vmstorage/main.go:97        opening storage at "/var/lib/victoria-metrics-data" with -retentionPeriod=1w
2022-05-19T08:02:27.132Z        info    VictoriaMetrics/lib/memory/memory.go:42 limiting caches to 1288490188 bytes, leaving 858993460 bytes to the OS according to -memory.allowedPercent=60
2022-05-19T08:02:27.132Z        info    VictoriaMetrics/lib/storage/storage.go:995      loading MetricName->TSID cache from "/var/lib/victoria-metrics-data/cache/metricName_tsid"...
2022-05-19T08:02:27.136Z        info    VictoriaMetrics/lib/storage/storage.go:1000     loaded MetricName->TSID cache from "/var/lib/victoria-metrics-data/cache/metricName_tsid" in 0.004 seconds; entriesCount: 0; sizeBytes: 0
2022-05-19T08:02:27.137Z        info    VictoriaMetrics/lib/storage/storage.go:995      loading MetricID->TSID cache from "/var/lib/victoria-metrics-data/cache/metricID_tsid"...
2022-05-19T08:02:27.141Z        info    VictoriaMetrics/lib/storage/storage.go:1000     loaded MetricID->TSID cache from "/var/lib/victoria-metrics-data/cache/metricID_tsid" in 0.004 seconds; entriesCount: 0; sizeBytes: 0
2022-05-19T08:02:27.141Z        info    VictoriaMetrics/lib/storage/storage.go:995      loading MetricID->MetricName cache from "/var/lib/victoria-metrics-data/cache/metricID_metricName"...
2022-05-19T08:02:27.145Z        info    VictoriaMetrics/lib/storage/storage.go:1000     loaded MetricID->MetricName cache from "/var/lib/victoria-metrics-data/cache/metricID_metricName" in 0.004 seconds; entriesCount: 0; sizeBytes: 0
2022-05-19T08:02:27.145Z        info    VictoriaMetrics/lib/storage/storage.go:844      loading curr_hour_metric_ids from "/var/lib/victoria-metrics-data/cache/curr_hour_metric_ids"...
2022-05-19T08:02:27.148Z        info    VictoriaMetrics/lib/storage/storage.go:866      discarding /var/lib/victoria-metrics-data/cache/curr_hour_metric_ids, since it contains outdated hour; got 458647; want 459152
2022-05-19T08:02:27.148Z        info    VictoriaMetrics/lib/storage/storage.go:844      loading prev_hour_metric_ids from "/var/lib/victoria-metrics-data/cache/prev_hour_metric_ids"...
2022-05-19T08:02:27.151Z        info    VictoriaMetrics/lib/storage/storage.go:866      discarding /var/lib/victoria-metrics-data/cache/prev_hour_metric_ids, since it contains outdated hour; got 458646; want 459151
2022-05-19T08:02:27.151Z        info    VictoriaMetrics/lib/storage/storage.go:800      loading next_day_metric_ids from "/var/lib/victoria-metrics-data/cache/next_day_metric_ids"...
2022-05-19T08:02:27.155Z        info    VictoriaMetrics/lib/storage/storage.go:820      discarding /var/lib/victoria-metrics-data/cache/next_day_metric_ids, since it contains data for stale date; got 19110; want 19131
2022-05-19T08:02:27.159Z        info    VictoriaMetrics/lib/mergeset/table.go:257       opening table "/var/lib/victoria-metrics-data/indexdb/16E9FDE083CD27BA"...
2022-05-19T08:02:27.279Z        info    VictoriaMetrics/lib/mergeset/table.go:292       table "/var/lib/victoria-metrics-data/indexdb/16E9FDE083CD27BA" has been opened in 0.120 seconds; partsCount: 6; blocksCount: 1328, itemsCount: 328348; sizeBytes: 10832831
2022-05-19T08:02:27.279Z        info    VictoriaMetrics/lib/mergeset/table.go:257       opening table "/var/lib/victoria-metrics-data/indexdb/16E9FDE083CD27B9"...
2022-05-19T08:02:27.413Z        info    VictoriaMetrics/lib/mergeset/table.go:292       table "/var/lib/victoria-metrics-data/indexdb/16E9FDE083CD27B9" has been opened in 0.133 seconds; partsCount: 5; blocksCount: 4251, itemsCount: 1593988; sizeBytes: 44978969
2022-05-19T08:02:27.478Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/10986_10986_20220430235940.391_20220430235944.222_16E9FDE0E21A32C1" in 0.010 seconds
2022-05-19T08:02:27.502Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/1109888_63656_20220430235120.542_20220430235922.183_16E9FDE0E21A32BC" in 0.022 seconds
2022-05-19T08:02:27.522Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/1133106_63658_20220430231326.526_20220430235203.449_16E9FDE0E21A3261" in 0.018 seconds
2022-05-19T08:02:27.534Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/1151343_63660_20220430233356.526_20220430234433.449_16E9FDE0E21A31FF" in 0.010 seconds
2022-05-19T08:02:27.545Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/12425_12425_20220430235929.662_20220430235934.360_16E9FDE0E21A32BF" in 0.010 seconds
2022-05-19T08:02:27.555Z        info    VictoriaMetrics/lib/storage/partition.go:1578   opened part "/var/lib/victoria-metrics-data/data/small/2022_04/1500_1500_20220430235922.144_20220430235925.462_16E9FDE0E21A32BD" in 0.007 seconds
2022-05-19T08:02:27.556Z        panic   VictoriaMetrics/lib/fs/reader_at.go:92  FATAL: cannot open file "/var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin" for reading: open /var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin: no such file or directory
panic: FATAL: cannot open file "/var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin" for reading: open /var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin: no such file or directory

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xacaf56, 0x5}, {0xc0000ccf20, 0x156}, 0x2?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:270 +0x965
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xacaf56, 0x5}, {0xae8bae?, 0x87?}, {0xc00099cf68?, 0xc00099cf38?, 0x45145c?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustOpenReaderAt({0xc000a3a630, 0x87})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go:92 +0xfb
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openFilePart({0xc0006f5780?, 0x78?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:58 +0x106
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openParts({0xc0007e84c0, 0x31}, {0xc000029bf0, 0x2f}, {0xc0007e84c0, 0x31})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1573 +0x875
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openPartition({0xc0007e84c0?, 0xc0000290b0?}, {0xc000029bf0, 0x2f}, 0xc0000021a0?, 0xc0000291f8?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:255 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openPartitions({0xc000028f30, 0x29}, {0xc0000290b0, 0x27}, 0x452057?, 0x23?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:514 +0x251
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openTable({0xc000028e70?, 0x7ffe37be3f85?}, 0xc000078010, 0x240c8400)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:119 +0x56f
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.OpenStorage({0x7ffe37be3f85?, 0xacaa44?}, 0x240c8400, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:260 +0xee5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage.InitWithoutMetrics(0xc39b30)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:100 +0x334
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage.Init(0x1?)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:75 +0x19
main.main()
        github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:55 +0x1f9
```		

There is no such file on the nas server: /var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin

Pod fails to start after server hard restart

I need to upgrade?
help

thanks

**Comment by marksugar** [comment]
refer to [63](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/63#issuecomment-500975055)
Data Corruption after power outage

i delete 
`/var/lib/victoria-metrics-data/data/small/2022_04/156147301_63916_20220428032742.318_20220428224426.526_16E9FDE0E219A07E/timestamps.bin`and
`/var/lib/victoria-metrics-data/data/big/2022_05/214395146_64268_20220501000001.024_20220502043841.200_16EAD21550E9DCC4/timestamps.bin`
pod up 
Partial data loss

**Comment by dmitryk-dk** [comment]
Hi @marksugar ! Thank you for you issue.
 What types of disks do you have? 
As a fast fix you can remove folder and run vm again

**Comment by marksugar** [comment]
hi @dmitryk-dk 
The shared storage I use is the [aliyun NAS](https://help.aliyun.com/document_detail/425537.html) file system, and the protocol is NFS v3/4.0
Dynamic pvc using StorageClass in k8s
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: victoriametrics
  namespace: monitoring
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  volumeAs: subpath
  server: "PATH=nas.aliyuncs.com:/victoriametrics/"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: victoriametrics
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: victoriametrics
  resources: 
    requests:
      storage: 380Gi
```
thanks

**Comment by dmitryk-dk** [comment]
Hi, @marksugar ! NFS system used buffer before save data to disk. VM always call fsync and safely save files to disk so that when you have unexpected power outage i think you data was in buffer.
