### ISSUE TITLE
vmagent runtime crash memory corruption

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2830]
**Describe the bug**

 at vmagent which was processing graphite random crash happened at 1.78 and 1.76 versions. It happened at different physical servers

**To Reproduce**
 No good way to reproduce.

**Expected behavior**
 vmagent shouldn't crash at data ingestion.

**Logs**
1.78
```
022-06-28T15:45:17+01:00		runtime/mgc.go:177 +0x6b
2022-06-28T15:45:17+01:00	created by runtime.gcenable
2022-06-28T15:45:17+01:00		runtime/asm_amd64.s:1571 +0x1 fp=0xc00005b7e8 sp=0xc00005b7e0 pc=0x468ba1
2022-06-28T15:45:17+01:00	runtime.goexit()
2022-06-28T15:45:17+01:00		runtime/mgc.go:177 +0x26 fp=0xc00005b7e0 sp=0xc00005b7c8 pc=0x41a186
2022-06-28T15:45:17+01:00	runtime.gcenable.func1()
2022-06-28T15:45:17+01:00		runtime/mgcsweep.go:281 +0x105 fp=0xc00005b7c8 sp=0xc00005b790 pc=0x4246a5
2022-06-28T15:45:17+01:00	runtime.bgsweep(0x0?)
2022-06-28T15:45:17+01:00		runtime/mgcsweep.go:369 +0xf0 fp=0xc00005b790 sp=0xc00005b740 pc=0x4248f0
2022-06-28T15:45:17+01:00	runtime.sweepone()
2022-06-28T15:45:17+01:00		runtime/mgcsweep.go:604 +0x338 fp=0xc00005b740 sp=0xc00005b668 pc=0x424ef8
2022-06-28T15:45:17+01:00	runtime.(*sweepLocked).sweep(0xdfb280?, 0x0)
2022-06-28T15:45:17+01:00		runtime/mgcsweep.go:776 +0x2e5 fp=0xc00005b668 sp=0xc00005b5e8 pc=0x425a65
2022-06-28T15:45:17+01:00	runtime.(*mspan).reportZombies(0x7fffd10c9f90)
2022-06-28T15:45:17+01:00		runtime/panic.go:992 +0x71 fp=0xc00005b5e8 sp=0xc00005b5b8 pc=0x436551
2022-06-28T15:45:17+01:00	runtime.throw({0x9d7671?, 0xc00027c6e0?})
2022-06-28T15:45:17+01:00	goroutine 3 [running]:
2022-06-28T15:45:17+01:00	
2022-06-28T15:45:17+01:00	fatal error: found pointer to free object
2022-06-28T15:45:17+01:00	0xc00027de40 free  unmarked
2022-06-28T15:45:17+01:00	0xc00027dce0 free  unmarked
2022-06-28T15:45:17+01:00	0xc00027c580 free  marked   zombie
2022-06-28T15:45:17+01:00	0xc00027c420 free  unmarked
2022-06-28T15:45:17+01:00	0xc00027c2c0 free  unmarked
2022-06-28T15:45:17+01:00	0xc00027c160 alloc marked  
2022-06-28T15:45:17+01:00	0xc00027c000 alloc marked  
2022-06-28T15:45:17+01:00	runtime: marked free object in span 0x7fffd10c9f90, elemsize=352 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
```
1.76
```
runtime: pointer 0xc0001fc100 to unallocated span span.base()=0xc0001f8000 span.limit=0xc000200000 span.state=0
runtime: found in object at *(0xc00101c008+0x0)
object=0xc00101c008 s.base()=0xc00101c000 s.limit=0xc00101e000 s.spanclass=2 s.elemsize=8 s.state=mSpanInUse
 *(object+0) = 0xc0001fc100 <==
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw({0x9c2631?, 0x6?})
	runtime/panic.go:992 +0x71 fp=0x7fffd1038c70 sp=0x7fffd1038c40 pc=0x4362f1
runtime.badPointer(0x7fffd0e12218, 0xc00004b738?, 0xc00101c008, 0x7fffd1038d38?)
	runtime/mbitmap.go:368 +0x150 fp=0x7fffd1038cc0 sp=0x7fffd1038c70 pc=0x414af0
runtime.findObject(0xc00101c008?, 0x7fffd1038d28?, 0x40c7c9?)
	runtime/mbitmap.go:410 +0xa6 fp=0x7fffd1038cf8 sp=0x7fffd1038cc0 pc=0x414c86
runtime.scanobject(0xc00004b738?, 0xc00004b738)
	runtime/mgcmark.go:1316 +0x190 fp=0x7fffd1038d90 sp=0x7fffd1038cf8 pc=0x41fb50
runtime.gcDrain(0xc00004b738, 0x3)
	runtime/mgcmark.go:1081 +0x1d4 fp=0x7fffd1038df0 sp=0x7fffd1038d90 pc=0x41f3b4
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:1276 +0xa5 fp=0x7fffd1038e40 sp=0x7fffd1038df0 pc=0x41c405
runtime.systemstack()
	runtime/asm_amd64.s:469 +0x49 fp=0x7fffd1038e48 sp=0x7fffd1038e40 pc=0x466729

goroutine 66 [GC worker (idle)]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:436 fp=0xc000286758 sp=0xc000286750 pc=0x4666c0
runtime.gcBgMarkWorker()
	runtime/mgc.go:1263 +0x1b1 fp=0xc0002867e0 sp=0xc000286758 pc=0x41c0d1
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc0002867e8 sp=0xc0002867e0 pc=0x4688e1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1131 +0x25
```

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./vmagent-prod --version
1.76/1.78
```

**Comment by valyala** [comment]
This issue can be related to https://github.com/golang/go/issues/37506 and https://github.com/golang/go/issues/37688

**Comment by valyala** [comment]
`vmagent` uses `cgo` only for compressing the last response for the scraped targets with the help of [gozstd](https://github.com/valyala/gozstd) package:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a6bd442ef9b8f93e40718af3ab45ddafb275f9d6/lib/promscrape/scrapework.go#L236-L256

The `gozstd` package is used actively by other VictoriaMetrics components for compressing on-disk data and for compressing the data transferred over the network between [cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html). If this package contains a bug with improper `cgo` usage, then this bug would trigger in other VictoriaMetrics components with high probability. But we are unaware of such bugs.

`vmagent` uses `unsafe` package for converting strings to byte slices and vice versa without memory allocation - see `bytesutil.ToUnsafeString` and `bytesutil.ToUnsafeBytes` functions:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a6bd442ef9b8f93e40718af3ab45ddafb275f9d6/lib/bytesutil/bytesutil.go#L64-L81

These functions are actively used VictoriaMetrics components. If these functions contain a bug of if they are improperly used, then the issue would be triggered in other VictoriaMetrics components with high probability. We didn't see such bugs yet.

According to the bugreport, it is reproduced starting from at least `v1.76`, which has been [released at April 12, 2022](https://docs.victoriametrics.com/CHANGELOG.html#v1760). We didn't receive similar bugreports for `vmagent` from other users in recent months yet.

Given the above facts the most likely causes of the issue are:

- Improper custom build for `vmagent`. It is recommended using the officially built binaries from [releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
- Bug in Go runtime, which triggers under certain conditions. For instance, if `vmagent` runs with small `GOGC` environment variable value, which increases the load on Go garbage collector, which, in turn, may increase the possibility for bug exposure.
- Hardware issues on the host where `vmagent` runs. See similar issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/581 .

**Comment by f41gh7** [comment]
VictoriaMetrics `golang` code looks safe and do not break any `unsafe` rules.

 Probably, there is an issue with some CGO dependencies and there is rare bug at `zstd` or `musl` compiler for C code.

 We could try `pure` build for `vmagent`.

**Comment by hagen1778** [comment]
Hey @f41gh7! Is this still a case? Have you seen reports about vmagent crashes?

**Comment by f41gh7** [comment]
> Hey @f41gh7! Is this still a case? Have you seen reports about vmagent crashes?

 No, I believe it's a hardware issue.
