### ISSUE TITLE
when doing retention，there has panic

### ISSUE THREAD

**Issue by gaoxp** [VictoriaMetrics/VictoriaMetrics#2914]
**Describe the bug**
we use vmstorage-20220714-171312-tags-v1.79.0-cluster-0-ga87f143e9 to run as a cluster,but after a night we find our some storage node has bee gone, and it can't startup, we check storage log, and find a panic that is "panic: runtime error: invalid memory address or nil pointer dereference"

**Logs**
```
VictoriaMetrics/lib/storage/index_db.go:310#011dropping indexDB "/data00/vm/vmdata/indexdb/17057C6B5DBCDC16"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.100Z#011info#011VictoriaMetrics/lib/storage/index_db.go:312#011indexDB "/data00/vm/vmdata/indexdb/17057C6B5DBCDC16" has been dropped
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.100Z#011info#011VictoriaMetrics/lib/mergeset/table.go:260#011opening table "/data00/vm/vmdata/indexdb/17057C6B5DBCDC19"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.102Z#011info#011VictoriaMetrics/lib/mergeset/table.go:296#011table "/data00/vm/vmdata/indexdb/17057C6B5DBCDC19" has been opened in 0.002 seconds; partsCount: 0; blocksCount: 0, itemsCount: 0; sizeBytes: 0
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:333#011waiting for raw items flusher to stop on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:336#011raw items flusher stopped in 0.000 seconds on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:338#011waiting for converters to stop on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:341#011converters stopped in 0.000 seconds on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:343#011waiting for part mergers to stop on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:346#011part mergers stopped in 0.000 seconds on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:348#011flushing inmemory parts to files on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:372#0110 inmemory parts have been flushed to files in 0.000 seconds on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:374#011waiting for flush callback worker to stop on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"...
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.103Z#011info#011VictoriaMetrics/lib/mergeset/table.go:377#011flush callback worker stopped in 0.000 seconds on "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.104Z#011info#011VictoriaMetrics/lib/storage/index_db.go:310#011dropping indexDB "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17"
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: 2022-07-26T20:54:00.107Z#011info#011VictoriaMetrics/lib/storage/index_db.go:312#011indexDB "/data00/vm/vmdata/indexdb/17057C6B5DBCDC17" has been dropped
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6df1b8]
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: goroutine 25 [running]:
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).getDeletedMetricIDs(...)
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:309
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getTSIDByMetricName(0x1836?, 0x1830?, {0xc0135d9a42?, 0x1837?, 0xc00fc78cc0?})
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:1774 +0x38
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).GetOrCreateTSIDByName(0xc012546140, 0xc00d314000, {0xc0135d9a42, 0xa3, 0x2e5be}, {0xc013410938, 0xb4, 0xe76c8}, 0x766eaa?)
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:545 +0xad
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).add(0xc0000001e0, {0xc00d314000, 0x1f40, 0x1f40}, {0xc009c90000, 0x1f40, 0x1f40}, {0xc00d1d8000, 0x1f40, 0x2ccc}, ...)
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:1958 +0x1194
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).AddRows(0xc0000001e0, {0xc00d1d8000, 0x2710, 0x2ccc}, 0xb2?)
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:1732 +0x394
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers.(*VMInsertServer).run.func1.3({0xc00d1d8000?, 0xc00088c960?, 0xc00029df18?})
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers/vminsert.go:115 +0x4a
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/clusternative.ParseStream.func1({0xc00d1d8000?, 0x0?, 0xc0005cc780?})
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/clusternative/streamparser.go:38 +0x39
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/clusternative.(*unmarshalWork).Unmarshal(0xc0129120c0)
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/clusternative/streamparser.go:155 +0x65
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/common.StartUnmarshalWorkers.func1()
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/common/unmarshal_work.go:35 +0x82
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: created by github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/common.StartUnmarshalWorkers
Jul 27 04:54:00 n209-148-172 vm-storage[2258855]: #011github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/common/unmarshal_work.go:32 +0xb4
```

**Version**
```
$  vmstorage-prod -version
vmstorage-20220714-171312-tags-v1.79.0-cluster-0-ga87f143e9
```

**Used command-line flags**
```
/usr/local/bin/vmstorage-prod \
   -enableTCP6 \
   -retentionPeriod=24h \
   -retentionTimezoneOffset=8h \
   -memory.allowedBytes=100GiB \
   -search.maxTagKeys=5000 \
   -search.maxTagValueSuffixesPerSearch=300000 \
   -search.maxTagValues=300000 \
   -smallMergeConcurrency=12 \
   -bigMergeConcurrency=8 \
   -storageDataPath=/data00/vm/vmdata
```

**Comment by f41gh7** [comment]
Hello, @gaoxp  may I ask you for the full log since node start-up? You can attach it as txt file. It seems that output was truncated, it may help to understand more about this panic.

 According to provided log, it may happen only if server where vmstorage runs, has an issue with corrupted memory.

**Comment by valyala** [comment]
It would be great to see other panic traces if they differ from the provided one

**Comment by gaoxp** [comment]
> Hello, @gaoxp may I ask you for the full log since node start-up? You can attach it as txt file. It seems that output was truncated, it may help to understand more about this panic.
> 
> According to provided log, it may happen only if server where vmstorage runs has an issue with corrupted memory.

We use v1.75.0-cluster instead of v1.79.0-cluster，the log has missed，on v1.75.0-cluster it works well.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if the problem still exists.
