### ISSUE TITLE
Possible panic under high load for vmselect v1.81.0

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#3058]
**Describe the bug**

Cluster version of [VictoriaMetrics v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.81.0) can crash with the following panic under high load:

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1545191 [running]:
sync.(*WaitGroup).Wait(0xc0fd5d1270?)
 sync/waitgroup.go:141 +0x85
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.ProcessBlocks(0x20121a843?, 0x5d?, 0xc000550780?, 0xc0139868d0, {0x1?, 0x0?, {0x92ca88?, 0x0?}})
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1394 +0x24b
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.ProcessSearchQuery(0x8ae2e0?, 0x0?, 0xc02531cdc0, {0x6311b57e, 0x8bb2c97000, {0x92ca88, 0x18}})
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1323 +0x332
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFuncWithMetricExpr(0x0, 0xc008cea240, {0xc106e4642c, 0x4}, 0x6bc852?, {0xaffc40, 0xc0fc710ea0}, 0xc00605de60, 0xc003feb020, 0xc0fd5d0d80)
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:1000 +0x8b9
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFuncWithoutAt(0x203000?, 0xc008cea240, {0xc106e4642c?, 0x8c06c0?}, 0x0?, {0xaffc40, 0xc0fc710ea0}, 0xc02531cb40, 0xc003feb020)
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:767 +0x519
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalRollupFunc(0xc0fd5d1230?, 0xc00023dc50?, {0xc106e4642c?, 0x3?}, 0x1?, {0xaffc40?, 0xc0fc710ea0?}, 0xc001a9405a?, 0x1?)
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:704 +0x465
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalAggrFunc(0xc106e46428?, 0xc008cea240, 0xc0fc710ea0)
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:354 +0x465
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExprInternal(0x44bc74?, 0xc008cea240, {0xaffc40?, 0xc0fc710ea0?})
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:287 +0x3a5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0xc007e04fb8?, 0x73a1bd?, {0xaffc40?, 0xc0fc710ea0?})
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:229 +0x267
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.execBinaryOpArgs.func2()
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:455 +0x85
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.execBinaryOpArgs
 github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:453 +0x67c
```

**To Reproduce**

Run [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) from the release [v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.81.0) with multiple `vmstorage` nodes and run multiple concurrent queries against the cluster. `vmselect` may sometimes panic with the message above.

**Expected behavior**
`vmselect` should correctly process all the incoming requests without any panics.

**Version**
The bug has been introduced in v1.81.0 in the commit ec3df0b913288c7a2104cbcc21ad062c94c1a171 . The previous releases have no bug.

**Possible workarounds**
To downgrade to [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.80.0) until the bug is fixed in v1.81.x.

**Comment by valyala** [comment]
The potential panic in `vmselect` under high load should be fixed in [VictoriaMetrics v1.81.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.81.1). Closing the issue then,

**Comment by nthienan** [comment]
still experience the issue. I have to roll back to v1.80.0

**Comment by dmitryk-dk** [comment]
Hi @nthienan ! Can you share some log if it is possible?

**Comment by nthienan** [comment]
there is no error log from vmselect. 
```
{"ts":"2022-09-07T15:54:24.628Z","level":"info","caller":"VictoriaMetrics/lib/memory/memory.go:42","msg":"limiting caches to 2751873024 bytes, leaving 687968256 bytes to the OS according to -memory.allowedPercent=80"}
{"ts":"2022-09-07T15:54:24.628Z","level":"info","caller":"VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:66","msg":"loading rollupResult cache from \"/vmcache/rollupResult\"..."}
{"ts":"2022-09-07T15:54:24.633Z","level":"info","caller":"VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:94","msg":"loaded rollupResult cache from \"/vmcache/rollupResult\" in 0.006 seconds; entriesCount: 17, sizeBytes: 1114112"}
{"ts":"2022-09-07T15:54:24.634Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:94","msg":"starting http server at http://127.0.0.1:8481/"}
{"ts":"2022-09-07T15:54:24.634Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:95","msg":"pprof handlers are exposed at http://127.0.0.1:8481/debug/pprof/"}
{"ts":"2022-09-07T15:54:32.643Z","level":"info","caller":"VictoriaMetrics/app/vmselect/querystats/querystats.go:87","msg":"enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms"}
```
However, my dashboards are crazy after upgrading to v1.81.0 and v1.81.1. Every time dashboard is refreshed, it shows different graph

<img width="742" alt="image" src="https://user-images.githubusercontent.com/10244759/188925711-08064620-c5ed-4775-b854-fb33bb523996.png">

<img width="730" alt="image" src="https://user-images.githubusercontent.com/10244759/188925856-8b0452b7-b1a9-4fdd-984a-f1f9fe620aff.png">

If I roll back vmselect to v1.80.0, the problem is gone. vmstorage and vminsert are still v1.81.1

**Comment by dmitryk-dk** [comment]
Hi @nthienan ! Thank you, we know that problem and work on it. It will be fixed soon

**Comment by dmitryk-dk** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3067
