### ISSUE TITLE
v1.83.1 version resource usage degradation

### ISSUE THREAD

**Issue by Alexul** [VictoriaMetrics/VictoriaMetrics#3343]
What happened: upgrade of single node from v1.82.1 (or v1.81.1) to v1.83.1

no changes in queries/ingested metrics, only upgrade resulted in CPU/mem spikes

<img width="1370" alt="Screenshot 2022-11-14 at 13 46 02" src="https://user-images.githubusercontent.com/10867201/201832829-a63719bb-9d86-4f8b-a84f-af422dddc694.png">
<img width="1371" alt="Screenshot 2022-11-14 at 13 28 35" src="https://user-images.githubusercontent.com/10867201/201832841-f6360e3d-5573-473b-b805-279dd11e07d7.png">

[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10009532/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10009533/mem.pprof.txt)

**Comment by valyala** [comment]
@Alexul , thanks for the detailed bugreport with screenshots and profiles! Could you try VictoriaMetrics from the docker image `docker.io/victoriametrics/victoria-metrics:heads-public-single-node-0-gc3362e3db` and share the updated screenshots of VictoriaMetrics dashboard, which cover the previous VictoriaMetrics release and the given docker image? The docker image includes [the fix](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/58b40f514ca2148749635e09c288d62ef150514c), which should reduce the pressure on Go garbage collector.

Additionally, [the commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c3362e3db472af2b95f06c88c4855b5547e32107) adds `-prevCacheRemovalPercent` command-line flag for fine tuning of cache lifetime. If the `docker.io/victoriametrics/victoria-metrics:heads-public-single-node-0-gc3362e3db` docker image won't reduce CPU usage comparing to the previous release, then could you try running it with the following values for `-prevCacheRemovalPercent` command-line flag and see whether this helps reducing CPU usage and doesn't increase memory usage:

* `-prevCacheRemovalPercent=0.1`
* `-prevCacheRemovalPercent=0.05`
* `-prevCacheRemovalPercent=0.01`
* `-prevCacheRemovalPercent=0`

**Comment by Alexul** [comment]
Hi @valyala , thanks for quick review!
Tried to run gc3362e3db but it crashes

`2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: victoria-metrics-20221116-104229-heads-public-single-node-0-gc3362e3db
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -bigMergeConcurrency="2"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpAuth.password="secret"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpAuth.username="wix"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -maxLabelsPerTimeseries="50"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -metricsAuthKey="secret"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="180d"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueryDuration="2m0s"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSeries="10000000"
2022-11-16T11:33:09.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxStalenessInterval="1m0s"
2022-11-16T11:33:09.488Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="10000000"
2022-11-16T11:33:09.488Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.treatDotsAsIsInRegexps="true"
2022-11-16T11:33:09.488Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -selfScrapeInterval="10s"
2022-11-16T11:33:09.488Z	info	VictoriaMetrics/app/victoria-metrics/main.go:54	starting VictoriaMetrics at ":8428"...
2022-11-16T11:33:09.488Z	info	VictoriaMetrics/app/vmstorage/main.go:114	opening storage at "victoria-metrics-data" with -retentionPeriod=180d
2022-11-16T11:33:09.490Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 909101386137 bytes, leaving 606067590759 bytes to the OS according to -memory.allowedPercent=60
2022-11-16T11:33:09.490Z	info	VictoriaMetrics/lib/storage/storage.go:1031	loading MetricName->TSID cache from "/victoria-metrics-data/cache/metricName_tsid"...
2022-11-16T11:33:09.876Z	info	VictoriaMetrics/lib/storage/storage.go:1036	loaded MetricName->TSID cache from "/victoria-metrics-data/cache/metricName_tsid" in 0.386 seconds; entriesCount: 0; sizeBytes: 0
2022-11-16T11:33:09.876Z	info	VictoriaMetrics/lib/storage/storage.go:1031	loading MetricID->TSID cache from "/victoria-metrics-data/cache/metricID_tsid"...
2022-11-16T11:33:09.923Z	info	VictoriaMetrics/lib/storage/storage.go:1036	loaded MetricID->TSID cache from "/victoria-metrics-data/cache/metricID_tsid" in 0.047 seconds; entriesCount: 0; sizeBytes: 0
2022-11-16T11:33:09.923Z	info	VictoriaMetrics/lib/storage/storage.go:1031	loading MetricID->MetricName cache from "/victoria-metrics-data/cache/metricID_metricName"...
2022-11-16T11:33:10.032Z	info	VictoriaMetrics/lib/storage/storage.go:1036	loaded MetricID->MetricName cache from "/victoria-metrics-data/cache/metricID_metricName" in 0.109 seconds; entriesCount: 0; sizeBytes: 0
2022-11-16T11:33:10.032Z	info	VictoriaMetrics/lib/storage/storage.go:891	loading curr_hour_metric_ids from "/victoria-metrics-data/cache/curr_hour_metric_ids"...
2022-11-16T11:33:10.319Z	info	VictoriaMetrics/lib/storage/storage.go:911	discarding /victoria-metrics-data/cache/curr_hour_metric_ids, since it contains outdated hour; got 1; want 463499
2022-11-16T11:33:10.319Z	info	VictoriaMetrics/lib/storage/storage.go:891	loading prev_hour_metric_ids from "/victoria-metrics-data/cache/prev_hour_metric_ids"...
2022-11-16T11:33:10.660Z	info	VictoriaMetrics/lib/storage/storage.go:911	discarding /victoria-metrics-data/cache/prev_hour_metric_ids, since it contains outdated hour; got 1; want 463498
2022-11-16T11:33:10.660Z	info	VictoriaMetrics/lib/storage/storage.go:847	loading next_day_metric_ids from "/victoria-metrics-data/cache/next_day_metric_ids"...
2022-11-16T11:33:10.784Z	info	VictoriaMetrics/lib/storage/storage.go:867	discarding /victoria-metrics-data/cache/next_day_metric_ids, since it contains data for stale date; got 18973; want 19312
2022-11-16T11:33:10.786Z	info	VictoriaMetrics/lib/mergeset/table.go:270	opening table "/victoria-metrics-data/indexdb/171190A6FF219D3E"...
2022-11-16T11:33:19.523Z	info	VictoriaMetrics/lib/mergeset/table.go:306	table "/victoria-metrics-data/indexdb/171190A6FF219D3E" has been opened in 8.736 seconds; partsCount: 63; blocksCount: 214428814, itemsCount: 55102793706; sizeBytes: 2296706015170
2022-11-16T11:33:19.541Z	info	VictoriaMetrics/lib/mergeset/table.go:270	opening table "/victoria-metrics-data/indexdb/16F7DB93E0B4ABC7"...
panic: runtime error: index out of range [94] with length 71

goroutine 200 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamReader).Next(0xc000202540)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/block_stream_reader.go:233 +0xc77
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).Merge(0xc048140dc0, 0xc0006442a0?, 0x3?, 0x7f792e245fe8?, 0x1a0?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:142 +0x1da
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mergeBlockStreams(0xc08c62c000?, 0xc07fe02eb0?, {0xc0006442a0, 0x3, 0x3}, 0x89f4280911cdeed3?, 0xcd1b542d6ec0d986?, 0x142803a507a76f1c?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:36 +0x10c
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc0001b03c0, {0xc000644288?, 0x3, 0x3}, 0xc0005b4001?, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:952 +0x811
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeExistingParts(0xc0001b03c0, 0x20?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:824 +0x12e
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).partMerger(0xc0001b03c0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:838 +0x6a
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:792 +0x26
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:791 +0x27`

**Comment by valyala** [comment]
@Alexul , could you try `heads-public-single-node-0-g5955d2323` docker image then?

**Comment by swoga** [comment]
Hello @valyala, we have also encountered this `index out of range` error, `g5955d2323` did solve it for us.

**Comment by Alexul** [comment]
Yes, not crashes anymore. Results so far: first restart 1.83.1->g5955d2323 second g5955d2323->g5955d2323 with -prevCacheRemovalPercent=0
<img width="1389" alt="Screenshot 2022-11-17 at 10 30 17" src="https://user-images.githubusercontent.com/10867201/202396181-a6e53fa8-d873-4d8e-917c-2083623ac5d6.png">
Whats the downside of running with 0? Unfortunately will not have time to run others today...

**Comment by valyala** [comment]
> Whats the downside of running with 0?

VictoriaMetrics puts various data into in-memory caches named [lib/workingsetcache](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/578bb58ea94cbfba6a0553827d5fca41dd94fc7c/lib/workingsetcache/cache.go). Every such cache consists of two parts - `current` (aka `curr`) and `previous` (aka `prev`). Cache lookups work in the following way:
1. The requested item is searched in the `curr` cache. If it is found there, then it is returned to the caller.
2. Otherwise the requested item is searched in the `prev` cache. If it is found there, then it is added to the `curr` cache and then returned to the caller. Next time the item will be found in the `curr` cache without the need to consult the `prev` cache.
3. If the item isn't found in both `curr` and `prev` cache, then it is re-constructed from the data stored on disk. This usually takes additional disk read IO for reading the needed data from disk. After that it takes additional CPU for unpacking the data read from disk before storing it in the `curr` cache.

Periodically the `prev` cache is reset, all the items from the `curr` cache are atomically moved to the `prev` cache and the `curr` cache is reset. This helps keeping frequently requested items in the cache, while dropping least recently requested items from the cache. Then frequently requested items tend to be located in both `curr` and `prev` caches, while least recently requested items migrate from the `curr` to the `prev` cache and then are removed from the cache on the next rotation.

The main benefit of this scheme is that it allows dropping unused items from the cache. The main downside of this scheme is that frequently requested items are stored in the cache two times - in the `curr` and the `prev` parts of the cache.

VictoriaMetrics v1.83.0 and newer versions include an optimization, which resets the `prev` cache as soon as it starts receiving small portion of incoming requests. This indicates that the majority of requests are satisfied with the `curr` cache. This should reduce the average memory usage for various in-memory caches by up to 50%. The threshold for `prev` cache removal can be controlled with the `-prevCacheRemovalPercent` command-line starting from the `heads-public-single-node-0-g5955d2323` docker image. The `-prevCacheRemovalPercent=0` disables this optimization by returning the caching behavior to pre-`v1.83.0`.

The `heads-public-single-node-0-g5955d2323` sets the threshold to 0.2% (e.g. when more than 100-0.2=99.8% of incoming requests are satisfied from the `curr` cache, then the `prev` cache is dropped). It looks like this value is much better than the previously hardcoded 1% value in `v1.83.1` for your workload according to resource usage graphs above. I reduced the default threshold from 0.2% to 0.1% in the commit 353396aa23fa79b7f609741f36ecba8ff63c204b - it would be great if you could verify whether this commit reduces resource usage further by running VictoriaMetrics from docker tag `heads-public-single-node-0-g353396aa2`.

**Comment by Alexul** [comment]
stats from  g5955d2323 with -prevCacheRemovalPercent=0 to g353396aa2 :
<img width="1388" alt="Screenshot 2022-11-19 at 09 47 15" src="https://user-images.githubusercontent.com/10867201/202840778-87e250c7-5bc5-410b-94aa-3546f8aca51b.png">
running fine, resident memory size drops from ~550MB to ~450MB but its not really "my" workload, its just a backup instance i can test on

**Comment by valyala** [comment]
@Alexul , thanks for the assistance with finding the optimal default value for `-prevCacheRemovalPercent` command-line flag (the value is `0.1`)! This value will be used starting from the next release.

**Comment by valyala** [comment]
This issue should be fixed in [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it then.
