### ISSUE TITLE
Failed to upgrade from 1.84 to 1.85.3

### ISSUE THREAD

**Issue by sergeyshaykhullin** [VictoriaMetrics/VictoriaMetrics#3580]
**Describe the bug**

nullref on 1.84 to 1.85.3 upgrade

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
```
{"ts":"2023-01-02T22:39:14.844Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/config.go:124","msg":"started service discovery routines in 0.126 seconds"}
{"ts":"2023-01-02T22:39:14.844Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:419","msg":"static_configs: added targets: 1, removed targets: 0; total targets: 1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x879e1a]

goroutine 87 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.labelsHash(0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/targetstatus.go:304 +0x5a
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*droppedTargets).Register(0xe60f10, 0x0, 0xc00019e300)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/targetstatus.go:280 +0x46
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWorkConfig).getScrapeWork(0xc000278f70, {0xc0002aca90, 0x10}, 0x7f49508d43c8?, 0x203000?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/config.go:1189 +0x4fb
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*ScrapeConfig).mustStart.func1(0xc00019e768?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/config.go:286 +0x7e
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes.getScrapeWorkObjectsForLabels(0xc00005fe70, {0xc000014ac0, 0x1, 0x1d?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:171 +0xa2
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes.(*groupWatcher).getScrapeWorkObjectsByAPIWatcherLocked.func1({0xc000308680, 0x1d}, {0xc000014ac0?, 0x1, 0x1})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:308 +0xf7
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes.(*groupWatcher).getScrapeWorkObjectsByAPIWatcherLocked
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:306 +0x1f3
```

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/grafana/dashboards/10229-victoriametrics/)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/)

See how to setup monitoring here:
* [monitoring for single-node VictoriaMetrics](https://docs.victoriametrics.com/#monitoring)
* [monitoring for VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55
```

**Used command-line flags**

```
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:12","msg":"build version: vmagent-20221220-230030-tags-v1.85.3-0-gf443fad56"}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:13","msg":"command-line flags"}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.enable=\"true\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -envflag.prefix=\"VM_\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -loggerFormat=\"json\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -memory.allowedPercent=\"40\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -promscrape.config=\"/config/scrape.yml\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -promscrape.dropOriginalLabels=\"true\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -promscrape.suppressDuplicateScrapeTargetErrors=\"true\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -remoteWrite.flushInterval=\"5s\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -remoteWrite.roundDigits=\"5\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -remoteWrite.tmpDataPath=\"/tmpData\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"  -remoteWrite.url=\"secret\""}
{"ts":"2023-01-02T22:39:14.711Z","level":"info","caller":"VictoriaMetrics/app/vmagent/main.go:103","msg":"starting vmagent at \":8429\"..."}
```

**Comment by zekker6** [comment]
@sergeyshaykhullin It seems like you are using `latest` tag to  run VictoriaMetrics with docker. This is not recommended since `latest` can contain some test versions not intended for regular use.
Could you try to use `v1.85.3` tag and check if issue is still present?

**Comment by sergeyshaykhullin** [comment]
@zekker6 I am running the latest version of vm agent helm chart without tag override

**Comment by zekker6** [comment]
@sergeyshaykhullin Could you share vmagent configuration you use for this vmagent?

**Comment by zekker6** [comment]
@sergeyshaykhullin Thanks for the configuration!

This issue has been fixed in #3595.
In the meantime could you set tag to `heads-fix-vmagent-crash-without-labels-kept-0-g2b19783a8`:
```yaml
image:
  tag: "heads-fix-vmagent-crash-without-labels-kept-0-g2b19783a8"
```

And check if your VMAgent now works as expected?

**Comment by sergeyshaykhullin** [comment]
@zekker6 Yes, this image is fixed panics

**Comment by valyala** [comment]
Re-opening the issue until the bugfix is included in the next release.

**Comment by valyala** [comment]
`vmagent` should properly work when it runs with `-promscrape.dropOriginalLabels` starting from [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
