### ISSUE TITLE
cannot move,  permission denied on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Nick135** [VictoriaMetrics/VictoriaMetrics#3621]
### Describe the bug

When I run VictoriaMetrics in wsl (Ubuntu), I always get "FATAL: cannot move" after a few minutes.
Working folder is on my local windows disk. File system is NTFS.

### To Reproduce

Run VictoriaMetrics on WSL v1, e.g. Ubuntu with workfolder on "/mnt/c/" and send data to the db.

### Version

victoria-metrics-20221220-225455-tags-v1.85.3-0-gf443fad56

### Logs

```
user@myPC:/mnt/d/#VictoriaMetrics/linux$ ./victoria-metrics-prod -retentionPeriod=100y
2023-01-05T15:51:55.422Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: victoria-metrics-20221220-225455-tags-v1.85.3-0-gf443fad56
2023-01-05T15:51:55.423Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2023-01-05T15:51:55.423Z        info    VictoriaMetrics/lib/logger/flag.go:20     -retentionPeriod="100y"
2023-01-05T15:51:55.423Z        info    VictoriaMetrics/app/victoria-metrics/main.go:58 starting VictoriaMetrics at ":8428"...
2023-01-05T15:51:55.423Z        info    VictoriaMetrics/app/vmstorage/main.go:114       opening storage at "victoria-metrics-data" with -retentionPeriod=100y
2023-01-05T15:51:55.428Z        info    VictoriaMetrics/lib/memory/memory.go:42 limiting caches to 40719170764 bytes, leaving 27146113844 bytes to the OS according to -memory.allowedPercent=60
2023-01-05T15:51:55.428Z        info    VictoriaMetrics/lib/storage/storage.go:1031     loading MetricName->TSID cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricName_tsid"...
2023-01-05T15:51:55.442Z        info    VictoriaMetrics/lib/storage/storage.go:1036     loaded MetricName->TSID cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricName_tsid" in 0.015 seconds; entriesCount: 0; sizeBytes: 0
2023-01-05T15:51:55.443Z        info    VictoriaMetrics/lib/storage/storage.go:1031     loading MetricID->TSID cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricID_tsid"...
2023-01-05T15:51:55.448Z        info    VictoriaMetrics/lib/storage/storage.go:1036     loaded MetricID->TSID cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricID_tsid" in 0.005 seconds; entriesCount: 0; sizeBytes: 0
2023-01-05T15:51:55.448Z        info    VictoriaMetrics/lib/storage/storage.go:1031     loading MetricID->MetricName cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricID_metricName"...
2023-01-05T15:51:55.453Z        info    VictoriaMetrics/lib/storage/storage.go:1036     loaded MetricID->MetricName cache from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/metricID_metricName" in 0.004 seconds; entriesCount: 0; sizeBytes: 0
2023-01-05T15:51:55.453Z        info    VictoriaMetrics/lib/storage/storage.go:891      loading curr_hour_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/curr_hour_metric_ids"...
2023-01-05T15:51:55.456Z        info    VictoriaMetrics/lib/storage/storage.go:926      loaded curr_hour_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/curr_hour_metric_ids" in 0.000 seconds; entriesCount: 0; sizeBytes: 16
2023-01-05T15:51:55.456Z        info    VictoriaMetrics/lib/storage/storage.go:891      loading prev_hour_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/prev_hour_metric_ids"...
2023-01-05T15:51:55.464Z        info    VictoriaMetrics/lib/storage/storage.go:926      loaded prev_hour_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/prev_hour_metric_ids" in 0.000 seconds; entriesCount: 0; sizeBytes: 16
2023-01-05T15:51:55.464Z        info    VictoriaMetrics/lib/storage/storage.go:847      loading next_day_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/next_day_metric_ids"...
2023-01-05T15:51:55.467Z        info    VictoriaMetrics/lib/storage/storage.go:882      loaded next_day_metric_ids from "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/cache/next_day_metric_ids" in 0.000 seconds; entriesCount: 0; sizeBytes: 16
2023-01-05T15:51:55.469Z        info    VictoriaMetrics/lib/mergeset/table.go:308       opening table "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/indexdb/17377252DB4B1F76"...
2023-01-05T15:51:55.488Z        info    VictoriaMetrics/lib/mergeset/table.go:343       table "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/indexdb/17377252DB4B1F76" has been opened in 0.019 seconds; partsCount: 2; blocksCount: 2, itemsCount: 380; sizeBytes: 4013
2023-01-05T15:51:55.490Z        info    VictoriaMetrics/lib/mergeset/table.go:308       opening table "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/indexdb/17377252DB4B1F75"...
2023-01-05T15:51:55.503Z        info    VictoriaMetrics/lib/mergeset/table.go:343       table "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/indexdb/17377252DB4B1F75" has been opened in 0.013 seconds; partsCount: 0; blocksCount: 0, itemsCount: 0; sizeBytes: 0
2023-01-05T15:51:55.588Z        info    VictoriaMetrics/lib/storage/partition.go:1909   opened part "/mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/1396_39_20230105154457.885_20230105154825.547_173774271B79C9C9" in 0.019 seconds
2023-01-05T15:51:55.602Z        info    VictoriaMetrics/app/vmstorage/main.go:131       successfully opened storage "victoria-metrics-data" in 0.177 seconds; partsCount: 1; blocksCount: 39; rowsCount: 1396; sizeBytes: 4686
2023-01-05T15:51:55.611Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:114  loading rollupResult cache from "victoria-metrics-data/cache/rollupResult"...
2023-01-05T15:51:55.616Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:142  loaded rollupResult cache from "victoria-metrics-data/cache/rollupResult" in 0.005 seconds; entriesCount: 0, sizeBytes: 0
2023-01-05T15:51:55.617Z        info    VictoriaMetrics/app/victoria-metrics/main.go:68 started VictoriaMetrics in 0.193 seconds
2023-01-05T15:51:55.617Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:96 starting http server at http://127.0.0.1:8428/
2023-01-05T15:51:55.620Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:97 pprof handlers are exposed at http://127.0.0.1:8428/debug/pprof/
2023-01-05T15:53:15.898Z        panic   VictoriaMetrics/lib/fs/fs.go:237        FATAL: cannot move /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1 to /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1.must-remove.1672933915418033321: rename /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1 /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1.must-remove.1672933915418033321: permission denied
panic: FATAL: cannot move /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1 to /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1.must-remove.1672933915418033321: rename /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1 /mnt/d/#VictoriaMetrics/linux/victoria-metrics-data/data/small/2023_01/18_11_20230105155239.562_20230105155239.685_173774885C2078B1.must-remove.1672933915418033321: permission denied

goroutine 165 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xb544ce, 0x5}, {0xc00b590000, 0x280}, 0x3?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa9d
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xb544ce, 0x5}, {0xb67170?, 0x2?}, {0xc0012d9878?, 0xc0012d9848?, 0x0?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1d6
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveDirAtomic({0xc00b582e00, 0x83})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs.go:237 +0x1d0
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.runTransaction(0xc000d64cc0?, {0xc000b14f00, 0x46}, {0xc000b14f50, 0x44}, {0xc000d64cc0, 0x5b})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:2078 +0x825
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).openCreatedPart(0xc0000ea300, 0xc0014680c0, {0xc000d2ad80?, 0xb, 0xc}, 0x0, {0xc000b14f00, 0x46}, {0xc000d64180, 0x5b}, ...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1510 +0x3c5
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc0000ea300, {0xc000d2ad80, 0xb, 0xc}, 0xc00003cc00?, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1341 +0x9e7
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc0000ea300, 0x40?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1182 +0x388
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc0000ea300)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1048 +0x7e
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1028 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1027 +0x37
```

### Used command-line flags

./victoria-metrics-prod -retentionPeriod=100y

### Additional information

Same Version works in a VMware with Ubuntu and workfolder on local vm disk.

**Comment by denisgolius** [comment]
Hi @Nick135 !
Please see my answer - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3236#issuecomment-1310516521.
As a workaround you can use docker/podman volumes or use ext[2...4]/xfs/zfs/btrfs filesystems.

BTW: we have plans to add full windows support but don't have ETA for this task.
