### ISSUE TITLE
Top-level vmselect is down with panic.

### ISSUE THREAD

**Issue by sonjoosik** [VictoriaMetrics/VictoriaMetrics#3734]
### Describe the bug

We were testing multi-level cluster settings and found a strange phenomenon. 

There are 2 different clusters containing the same data. (They are twins.) And a top-level vmselect is collecting data from both of them with a replication factor of 2. We wanted to test what happens if one of the clusters is down, so we killed the vmstorage process in a cluster. Then, we sent a query through Vmui with the trace flag. After that, the top-level vmselect was down. 

### To Reproduce

1. Set a multi-level cluster with 2 second-level clusters.
2. Run the top-level vmselect with `replicationFactor` = 2. 
3. Kill one of the second-level clusters.
4. Send a query via `Vmui` of top-level vmselect with `trace flag`.  (You may have to try several times to reproduce this.)

### Version

vmselect-20221220-230702-tags-v1.85.3-cluster-0-g30b15111a

### Logs

* The first try
~~~
2023-02-01T01:18:47.107Z        info    VictoriaMetrics/app/vmselect/querystats/querystats.go:87        enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
panic: BUG: NewChild() cannot be called after Donef("rpc at vmstorage asca1x1191.nfra.io:8801: cancel request because 1 out of 2 nodes already returned response according to -replicationFactor=2") call

goroutine 1736403 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer.(*Tracer).NewChild(0x990c87?, {0x99eca0?, 0x908980?}, {0xc0012a9dd8?, 0xc0097cde40?, 0x63d9c20f?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer/tracer.go:72 +0x23a
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).execOnConnWithPossibleRetry(0x9402e0?, 0xc00ec45db0?, {0x990c87, 0x9}, 0x10?, {0x7ff01bf3a108?, 0x10?, {0x9989da?, 0xc014b12420?}})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1864 +0x22e
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).processSearchQuery(0xb5c110?, 0xc0097cdee0?, {0xc00721d280?, 0x469b6e?, 0x43b087?}, 0xc0097cded8?, 0x43b0c0?, {0x63d9c20f, 0x6fc23ac00, {0x9989da, ...}})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1847 +0xa6
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.processBlocks.func2(0x642c5e?, 0xc007276150?, 0xc0003d2000)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1468 +0x116
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest.func1(0x642ac6?, 0xc007276150?)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1517 +0x39
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1516 +0x7d
~~~

* The second try
~~~
2023-02-01T01:40:27.268Z        info    VictoriaMetrics/app/vmselect/querystats/querystats.go:87        enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
2023-02-01T01:41:18.060Z        warn    VictoriaMetrics/app/vmselect/main.go:674        error in "/select/0/prometheus/api/v1/label/__name__/values": cannot obtain values for label "__name__": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage asca1x1191.nfra.io:8801: cannot execute funcName="labelValues_v5" on vmstorage "10.168.210.216:8801": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage :8401: cannot obtain connection from a pool: cannot dial :8401: dial tcp4 :8401: connect: connection refused
2023-02-01T01:41:27.045Z        warn    VictoriaMetrics/app/vmselect/main.go:674        error in "/select/0/prometheus/api/v1/label/__name__/values": cannot obtain values for label "__name__": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage asca1x1191.nfra.io:8801: cannot execute funcName="labelValues_v5" on vmstorage "10.168.210.216:8801": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage :8401: cannot obtain connection from a pool: cannot dial :8401: dial tcp4 :8401: connect: connection refused
2023-02-01T01:41:27.076Z        warn    VictoriaMetrics/app/vmselect/main.go:674        error in "/select/0/prometheus/api/v1/query_range?query=sum(sas%3Aperf_qps%7Bssuid%3D%22web%22))&start=1675213886.094&end=1675215686.094&step=3.069": error when executing query="sum(sas:perf_qps{ssuid=\"web\"))" on the time range (start=1675213886094, end=1675215686094, step=3069): labelFilters: unexpected token ")"; want ",", "}"; unparsed data: "))"
panic: BUG: NewChild() cannot be called after Donef("rpc at vmstorage asca1x1191.nfra.io:8801: cancel request because 1 out of 2 nodes already returned response according to -replicationFactor=2") call

goroutine 263212 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer.(*Tracer).NewChild(0x990c87?, {0x99eca0?, 0x908980?}, {0xc002b91dd8?, 0xc002b91e40?, 0x63d9c36b?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer/tracer.go:72 +0x23a
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).execOnConnWithPossibleRetry(0xc0143b1f38?, 0x44b414?, {0x990c87, 0x9}, 0x10?, {0x7fe61ab3db38?, 0x10?, {0x9989da?, 0xc00e824340?}})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1864 +0x22e
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).processSearchQuery(0xc0143b1ef8?, 0x3?, {0xc0397c62c0?, 0x0?, 0xc0143b1fb0?}, 0xc02441abf8?, 0xc02441ab40?, {0x63d9c36b, 0x6fc23ac00, {0x9989da, ...}})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1847 +0xa6
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.processBlocks.func2(0x642c01?, 0xb5a548?, 0xc000016540)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1468 +0x116
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest.func1(0xc03b33a480?, 0x0?)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1517 +0x39
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1516 +0x7d
~~~

**Comment by zekker6** [comment]
@sonjoosik Thank you for the detailed bug report!

This issue has been fixed in #3738.
You can use this docker image to check if it helps:  `victoriametrics/vmselect:heads-fix-vmselect-multilevel-trace-panic-0-ge998bc88e`
Or use [this instruction](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-build-from-sources) to build from source.

**Comment by sonjoosik** [comment]
@zekker6 
Thank you for the quick fix!

**Comment by valyala** [comment]
The bugfix has been included in [VictoriaMetrics v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by valyala** [comment]
This issue has been also fixed in [v1.79.8 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.8).

**Comment by BenNF** [comment]
We seem to still be experiencing this bug(or a variant of it) in 1.87.5.

Stack trace

```
panic: BUG: NewChild() cannot be called after Donef("rpc at vmstorage storageset-icebox-storage-6.storageset-icebox-storage.vm-abbot.svc.iad03.k8s.run:8401: cancel request because 71 out of 72 nodes already returned response according to -replicationFactor=2") call
--
github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer.(*Tracer).NewChild(0x998294?, {0x99a00c?, 0x998294?}, {0xc0e70a5dd0?, 0xc0e70a5e40?, 0x64e5194b?})
github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer/tracer.go:72 +0x23a
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).processSearchQuery(0xc0001ad5c0?, 0xc05cf95b00?, {0xc032107080?, 0x60?, 0x80?}, 0xc017409ce0?, 0x39?, {0x64e5194b, 0x9184e72a000, {0x9a0193, ...}})
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1987 +0xa6
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).execOnConnWithPossibleRetry(0xc009380c60?, 0x10?, {0x998294, 0x9}, 0x0?, {0x7fc662092d20?, 0x7fc6916323c8?, {0x9a0193?, 0xc02f9dc400?}})
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1656 +0x7d
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1657 +0x39
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.processBlocks.func2(0x0?, 0x0?, 0xc0001ad5c0)
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1991 +0xde
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1608 +0x116
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest.func1(0x0?, 0x0?)
```

With the following flags on vmselect 

```
  - "--httpListenAddr=127.0.0.1:8481"
  - "--replicationFactor=2"
```

We are not querying with multilevel select here despite the flag being enabled. 

We've been able to mitigate this by setting `--replicationFactor=1` which resolves the issue on our trace queries.

**Comment by hagen1778** [comment]
Hello @BenNF! Do you still experience the same behavior on newer versions of vmselect? (1.97+)
