### ISSUE TITLE
vmstorage: panic: FATAL: cannot open file for reading: operation not permitted

### ISSUE THREAD

**Issue by wulingling0108** [VictoriaMetrics/VictoriaMetrics#4396]
### Is your question request related to a specific component?

vmstorage-prod: panic: FATAL: cannot open file for reading: open /data/vmstorage-data/data/small/2023_06/114017_52311_20230603015105.522_20230603015137.543_1764B4B3F9B52EC9/values.bin: operation not permitted

### Describe the question in detail

Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: 2023-06-05T11:30:53.313+0800#011panic#011VictoriaMetrics/lib/fs/reader_at.go:122#011FATAL: cannot open file for reading: open /data/vmstorage-data/data/small/2023_06/114017_52311_20230603015105.522_20230603015137.543_1764B4B3F9B52EC9/values.bin: operation not permitted
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: panic: FATAL: cannot open file for reading: open /data/vmstorage-data/data/small/2023_06/114017_52311_20230603015105.522_20230603015137.543_1764B4B3F9B52EC9/values.bin: operation not permitted
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: goroutine 1 [running]:
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x917ba2, 0x5}, {0xc000218180, 0xb9}, 0x1?)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x917ba2, 0x5}, {0x92baf5?, 0x452e06?}, {0xc0001bef40?, 0x76?, 0xc0001bef90?})
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustOpenReaderAt({0xc0001e2580, 0x76})
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go:122 +0x99
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openFilePart({0xc000974070?, 0x6b?})
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:62 +0x15f
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openParts({0xc0000bc720, 0x27}, {0xc0000bc750, 0x25}, {0xc0000bc720, 0x27})
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1927 +0x7d4
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openPartition({0xc0000bc720?, 0xc0000e6120?}, {0xc0000bc750, 0x25}, 0x0?)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:269 +0x196
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openPartitions({0xc0000e6060, 0x1f}, {0xc0000e6120, 0x1d}, 0x7fdef3d9f5b8?)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:516 +0x246
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.openTable({0xc0000e6000?, 0x7ffe886dff2a?}, 0xc0000ea380)
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:121 +0x645
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.OpenStorage({0x7ffe886dff2a?, 0x917891?}, 0x9a7ec800, 0x0, 0x0)
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: vmstorage.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:270 +0xeaf
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: main.main()
Jun  5 11:30:53 it-prod-sxvmrws1 vmstorage-prod: github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:99 +0x4e5
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: Unit vmstorage.service entered failed state.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: vmstorage.service failed.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: vmstorage.service holdoff time over, scheduling restart.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: Stopped Vmstorage Server.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: start request repeated too quickly for vmstorage.service
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: Failed to start Vmstorage Server.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: Unit vmstorage.service entered failed state.
Jun  5 11:30:53 it-prod-sxvmrws1 systemd: vmstorage.service failed.
Jun  5 11:30:54 it-prod-sxvmrws1 vminsert-prod: 2023-06-05T03:30:54.201Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:211#011cannot push 1467695 bytes with 2000 rows to storage nodes, since all the nodes are temporarily unavailable; re-trying to send the data soon
Jun  5 11:30:55 it-prod-sxvmrws1 vminsert-prod: 2023-06-05T03:30:55.072Z#011warn#011VictoriaMetrics/app/vminsert/main.go:239#011remoteAddr: "172.17.20.59:27691"; requestURI: /insert/0/prometheus; cannot read compressed request in 60 seconds: cannot process insert request for 60.000 seconds because 16 concurrent insert requests are executed. Possible solutions: to reduce workload; to increase compute resources at the server; to increase -insert.maxQueueDuration; to increase -maxConcurrentInserts
Jun  5 11:30:59 it-prod-sxvmrws1 vminsert-prod: 2023-06-05T03:30:59.217Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:211#011cannot push 1467695 bytes with 2000 rows to storage nodes, since all the nodes are temporarily unavailable; re-trying to send the data soon
Jun  5 11:31:04 it-prod-sxvmrws1 vminsert-prod: 2023-06-05T03:31:04.233Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:211#011cannot push 1467695 bytes with 2000 rows to storage nodes, since all the nodes are temporarily unavailable; re-trying to send the data soon
^Z

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @wulingling0108! 
The problem might be caused by your filesystem. Could you please skim through https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3881 and check if it is related to what you observe?

**Comment by jiekun** [comment]
Closing for inactivity
