### ISSUE TITLE
vmselect panics on 1 + on() 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4422]
### Describe the bug

vmselect panics when executes `query=1 + (on ())` query via api/v1/query endpoint 

stacktrace 

```panic: BUG: cannot parse the expression "1 + on()": singleExpr: unexpected token ""; want "(", "{", "-", "+"; unparsed data: ""

goroutine 92 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:227 +0x65
panic({0x8cb720, 0xc0000eeac0})
	runtime/panic.go:890 +0x262
github.com/VictoriaMetrics/metricsql.Clone({0xb01100?, 0xc0002c4750?})
	github.com/VictoriaMetrics/metricsql@v0.44.1/optimizer.go:52 +0xf3
github.com/VictoriaMetrics/metricsql.Optimize({0xb01100, 0xc0002c4750})
	github.com/VictoriaMetrics/metricsql@v0.44.1/optimizer.go:20 +0x38
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.parsePromQLWithCache({0xc000136493, 0xb})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/exec.go:252 +0x6c
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.IsMetricSelectorWithRollup({0xc000136493?, 0x925081?})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/parser.go:28 +0x25
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.QueryHandler(0x0, {0xc00033e000?, 0x2?, 0xd6e260?}, 0xc0001364a0, {0xb03810, 0xc00033e000}, 0xc0001dc000)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus/prometheus.go:748 +0x345
main.selectHandler(0xc0005880cd?, {0x1?, 0x924b59?, 0xd6e260?}, {0xb03810, 0xc00033e000}, 0xc0001dc000, 0xc0001768d0, 0xc0001364a0)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/main.go:368 +0xefb
main.requestHandler({0xb03810?, 0xc00033e000}, 0xc0001dc000)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/main.go:254 +0x833
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc00027a350, {0xb03810?, 0xc00033e000}, 0xc0001dc000, 0xa86f30)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:335 +0xdcd
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xb03810?, 0xc00033e000?}, 0xc000176690?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:195 +0x76
net/http.HandlerFunc.ServeHTTP(0x0?, {0xb03810?, 0xc00033e000?}, 0x656194?)
	net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0xb02ec0?}, {0xb03810, 0xc00033e000}, 0xc0001dc000)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000000960, {0xb03d80, 0xc000176390})
	net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x4db
```

### To Reproduce

- open vmui
- open table
- specify `query=1 + (on ())` in query input
- execute the query 

### Version

v1.82+, reproduced in the latest

**Comment by valyala** [comment]
The issue must be fixed in the following commits:

- Single-node VictoriaMetrics - e2367b6d1c5dcb941ad5dc24788ffbcbb81694de
- Cluster VictoriaMetrics - 781947a7e293417324ad482c6e505c5020f19fa6

These commits will be included in the next release. In the mean time it is possible to verify the fix by building VictoriaMetrics from these commits according to the following docs:

- [How to build single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-build-from-sources)
- [How to build cluster VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources)

**Comment by valyala** [comment]
VictoriaMetrics should properly handle `1 + (on)` queries starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
