### ISSUE TITLE
victoria-logs records combined multiline log entries separately

### ISSUE THREAD

**Issue by kukumber** [VictoriaMetrics/VictoriaMetrics#4510]
### Describe the bug

When attempting to send multiline log file entries with filebeat on the victoria-logs side each line is recorded separately.

### To Reproduce

I have the filebeat.yml:

```yaml
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - somelog2
    - somelog1
  multiline.type: pattern
  multiline.pattern: '^\d'
  multiline.negate: true
  multiline.match: after

output.elasticsearch:
  hosts: ["http://monitoring.domain.com:9428/insert/elasticsearch/"]
  bulk_max_size: 1000
  parameters:
    _msg_field: "message"
    _time_field: "@timestamp"
    _stream_fields: "host.name,log.file.path"
```

The multiline entry from my log file looks like this:

```
2023-06-22 15:49:44,651 [ERROR][93378][myservice] Exception with process at myserver.domain.com
Traceback (most recent call last):
  File "sender.py", line 106, in __call__
    desc=f"msg to {exch} on {srv}"
  File "helpers.py", line 8, in raise_on_timeout
    res = rabbit.wait(promise, timeout=timeout)
  File "connection.py", line 364, in wait
    raise_errors=raise_errors)
  File "promise.py", line 35, in run_callback
    return self._promises[number].run_callback(**kwargs)
  File "promise.py", line 132, in run_callback
    raise result.exception
ConnectionBroken
```

### Version

```
/victoria-logs-prod --version
victoria-logs-20230622-042603-tags-v0.1.0-victorialogs-0-g83aa78dfb
```

### Logs

There are no errors or warnings in the victoria-logs logs.

### Used command-line flags

```
-storageDataPath=/vlogs
```

**Comment by zekker6** [comment]
Hi @kukumber 
I've just tried to reproduce this and found out that fliebeat sends this trace as a set of separate messages so VictoriaLogs stores those as a separate messages as well.

As per this [doc](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/#http-parameters) it is possible to add `debug` parameter in order to make VictoriaLogs to print ingested rows instead of saving those.
Here is a log which I've received with `debug` enabled:
```
2023-06-23T08:05:17.663Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"2023-06-22 15:49:44,651 [ERROR][93378][myservice] Exception with process at myserver.domain.com","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1718"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"Traceback (most recent call last):","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1814"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"  File \"sender.py\", line 106, in __call__","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1849"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"    desc=f\"msg to {exch} on {srv}\"","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1891"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"  File \"helpers.py\", line 8, in raise_on_timeout","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1926"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"    res = rabbit.wait(promise, timeout=timeout)","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"1975"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"  File \"connection.py\", line 364, in wait","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2023"}
2023-06-23T08:05:17.664Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"    raise_errors=raise_errors)","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2065"}
2023-06-23T08:05:17.665Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"  File \"promise.py\", line 35, in run_callback","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2096"}
2023-06-23T08:05:17.665Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"    return self._promises[number].run_callback(**kwargs)","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2142"}
2023-06-23T08:05:17.665Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"  File \"promise.py\", line 132, in run_callback","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2199"}
2023-06-23T08:05:17.665Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"    raise result.exception","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2246"}
2023-06-23T08:05:17.665Z        info    /vlinsert/insertutils/common_params.go:80       remoteAddr="192.168.192.2:33866"; requestURI=/insert/elasticsearch/_bulk?_msg_field=message&_stream_fields=container.name&_time_field=%40timestamp&debug=true; ignoring log entry because of `debug` query arg: {"_msg":"ConnectionBroken","_stream":"{}","_time":"2023-06-23T08:05:16.653Z","agent.ephemeral_id":"96266592-6971-456e-9549-18cfc49a6b92","agent.id":"624856f6-ca37-47f8-a202-d71912a831a9","agent.name":"c45f4fe92ce8","agent.type":"filebeat","agent.version":"8.8.1","ecs.version":"8.0.0","host.name":"c45f4fe92ce8","input.type":"filestream","log.file.path":"/var/log/some/python.log","log.offset":"2273"}
```

Any chance you have it successfully working with some other ElasticSearch-compatible storage and filebeat?

**Comment by kukumber** [comment]
@zekker6 I've double checked our prod environment and found that we use the following scheme:

**filebeat -> logstash -> elastic search**

In this scheme everything works correctly.

I'll check the behaviour of multiline entries without the logstash in between and return with the results.

**Comment by zekker6** [comment]
@kukumber Just as FYI - VictoriaLogs supports ingesting from logstash as well, please see https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/Logstash.html for examples.

**Comment by kukumber** [comment]
@zekker6 I've checked it. Unfortunately, the elastic search also writes multiline as separate records:
``` 
19:27:39.682 2023-06-22 15:49:44,651 [ERROR][93378][myservice] Exception with process at myserver.domain.com
19:27:39.682 Traceback (most recent call last):
19:27:39.682    File "sender.py", line 106, in __call__
19:27:39.682      desc=f"msg to {exch} on {srv}"
19:27:39.682    File "helpers.py", line 8, in raise_on_timeout
19:27:39.682      res = rabbit.wait(promise, timeout=timeout)
19:27:39.682    File "connection.py", line 364, in wait
19:27:39.682      raise_errors=raise_errors)
19:27:39.682    File "promise.py", line 35, in run_callback
19:27:39.682      return self._promises[number].run_callback(**kwargs)
19:27:39.682    File "promise.py", line 132, in run_callback
19:27:39.682      raise result.exception
19:27:39.683 ConnectionBroken
```

It's not a bug, but feature :)
Is it possible to convert the current issue from bug into the feature request?

**Comment by zekker6** [comment]
@kukumber I'm afraid this fix should not be a part of VictoriaLogs, but a part of log shipping pipeline. We will definitely want to add documentation examples to cover this so that filebeat will join multiline logs into a single entry.

**Comment by kukumber** [comment]
@zekker6 got it, thanks
