### ISSUE TITLE
vmctl: remote-read panic

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#4553]
### Describe the bug

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc6c12a]

goroutine 1 [running]:
main.(*remoteReadProcessor).run(0xc000604a40, {0x1234620?, 0xc0009105a0}, 0x0, 0x0?)
        /home/thomas/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.91.3/app/vmctl/remoteread.go:35 +0x14a
main.main.func3(0xc000152c60?)
        /home/thomas/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.91.3/app/vmctl/main.go:157 +0x5ec
github.com/urfave/cli/v2.(*Command).Run(0xc000152c60, 0xc0000cea40, {0xc000358240, 0x6, 0x6})
        /home/thomas/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc00056e2c0, 0xc0000ce280, {0xc000036070, 0x7, 0x7})
        /home/thomas/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc00033c780, {0x1234658?, 0xc000040130}, {0xc000036070, 0x7, 0x7})
        /home/thomas/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /home/thomas/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:309
main.main()
        /home/thomas/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.91.3/app/vmctl/main.go:304 +0x1385
exit status 2
```

### To Reproduce

```
❯ go run github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl@latest remote-read --remote-read-src-addr=http://127.0.0.1:8080/prometheus --remote-read-step-interval=hour --remote-read-use-stream=true --vm-addr=http://127.0.0.1:8480 --vm-concurrency=6
```

### Version

v1.91.3

**Comment by boufleur** [comment]
I've got the same issue. To make it work, I had to set `--remote-read-filter-time-start`, even though it's not documented as a mandatory flag.

**Comment by valyala** [comment]
The `--remote-read-filter-time-start` flag is required for [Prometheus remote read mode](https://docs.victoriametrics.com/vmctl.html#migrating-data-by-remote-read-protocol) in [vmui](https://docs.victoriametrics.com/vmui.html) starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the issue as fixed.

**Comment by valyala** [comment]
FYI, the bugfix has been back-ported to [the long-term support release v1.87.7](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.7).
