### ISSUE TITLE
Can't create a snapshot (Connection was reset)

### ISSUE THREAD

**Issue by tekert** [VictoriaMetrics/VictoriaMetrics#4680]
### Describe the bug

```
>curl http://127.0.0.1:8428/snapshot/create
curl: (56) Recv failure: Connection was reset
```

```
>vmbackup output:
2023-07-20T12:19:13.685-0300    fatal   VictoriaMetrics/app/vmbackup/main.go:82 cannot create snapshot: Get "http://localhost:8428/snapshot/create": read tcp 127.0.0.1:54741->127.0.0.1:8428: wsarecv: An existing connection was forcibly closed by the remote host.
```

```
>curl http://127.0.0.1:8428/snapshot/list
{"status":"ok","snapshots":[]}
```

The server is working, when the snapshot/create is received, the server creates a new folder under
`<victoria-metrics-data>/data/small/snapshots`
`<victoria-metrics-data>/data/big/snapshots`

`small/snapshots` is populated with a new `20230720151913-17739BF7384D9B5D` subdir, when i try to delete it i can't, its in use, all the `*.bin` files can't be deleted.

Nothing is in the logs, i don't know why it refuses to snapshot.

### To Reproduce

curl http://127.0.0.1:8428/snapshot/create

### Version

victoria-metrics-20230630-144531-tags-v1.91.3-enterprise-0-gcbdc685e4e

### Used command-line flags

-promscrape.config="%VICTORIAMETRICS%\victoriametrics.yml" -retentionPeriod=10y -inmemoryDataFlushInterval=120s -downsampling.period=24h:10s,1w:30s,30d:1m,360d:5m

### Additional information

Windows Server 2019 as a service.
Run As "Local Service"
All folders have complete access for Local Service.

**Comment by zekker6** [comment]
@tekert Could you also share logs created by your VictoriaMetrics server instance?
Most likely it will contain error message there.

**Comment by tekert** [comment]
Hi zek, sorry, here is the relevant section when this command is executed, dind't see them before, seems the process resets when this error occurs from the first time and deletes the handler that flushes the output to a txt file, triggering the command a second time i could get the logs.

```
2023-07-24T12:14:51.684Z	info	VictoriaMetrics/lib/storage/storage.go:301	creating Storage snapshot for "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data"...
2023-07-24T12:14:51.685Z	info	VictoriaMetrics/lib/storage/table.go:135	creating table snapshot of "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data"...
2023-07-24T12:14:51.685Z	info	VictoriaMetrics/lib/storage/partition.go:1862	creating partition snapshot of "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_07" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_07"...
2023-07-24T12:14:51.909Z	info	VictoriaMetrics/lib/storage/partition.go:1889	created partition snapshot of "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_07" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_07" at "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\snapshots\\20230724121451-17739EE4BD424BED\\2023_07" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\snapshots\\20230724121451-17739EE4BD424BED\\2023_07" in 0.223 seconds
2023-07-24T12:14:51.909Z	info	VictoriaMetrics/lib/storage/partition.go:1862	creating partition snapshot of "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_06"...
2023-07-24T12:14:51.950Z	info	VictoriaMetrics/lib/storage/partition.go:1889	created partition snapshot of "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_06" at "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\snapshots\\20230724121451-17739EE4BD424BED\\2023_06" and "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\snapshots\\20230724121451-17739EE4BD424BED\\2023_06" in 0.042 seconds
2023-07-24T12:14:51.950Z	info	VictoriaMetrics/lib/storage/table.go:164	created table snapshot for "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data" at ("C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\snapshots\\20230724121451-17739EE4BD424BED", "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\snapshots\\20230724121451-17739EE4BD424BED") in 0.266 seconds
2023-07-24T12:14:51.962Z	panic	VictoriaMetrics/lib/fs/fs.go:294	FATAL: cannot make a symlink: symlink ..\..\..\data\small\snapshots\20230724121451-17739EE4BD424BED C:\Monitoring\victoria-metrics\victoria-metrics-data\snapshots\20230724121451-17739EE4BD424BED\data\small: A required privilege is not held by the client.
2023-07-24T12:14:52.010Z	panic	VictoriaMetrics/lib/fs/dir_remover.go:53	FATAL: cannot remove "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\snapshots\\20230724121451-17739EE4BD424BED": remove C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\snapshots\20230724121451-17739EE4BD424BED\2023_06\176ED613C2B5507D\index.bin: Access is denied.
panic: FATAL: cannot remove "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\snapshots\\20230724121451-17739EE4BD424BED": remove C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\snapshots\20230724121451-17739EE4BD424BED\2023_06\176ED613C2B5507D\index.bin: Access is denied.

goroutine 493009 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:235 +0x65
panic({0x8b9de0, 0xc000646df0})
	runtime/panic.go:890 +0x263
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x96daa1, 0x5}, {0xc010c03180, 0x12f}, 0x2?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x96daa1, 0x5}, {0x97f2b4?, 0x0?}, {0xc000abcb48?, 0x6f74636976223d6e?, 0x7274656d2d616972?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.tryRemoveAll({0xc014178080, 0x69})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/dir_remover.go:53 +0x10e
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveAll({0xc014178080, 0x69})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/dir_remover.go:19 +0x2a
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).CreateSnapshot.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:310 +0x3e
panic({0x8b9de0, 0xc000646b60})
	runtime/panic.go:884 +0x213
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x96daa1, 0x5}, {0xc00725f800, 0xfe}, 0x1?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x96daa1, 0x5}, {0x98598d?, 0xc0029cce10?}, {0xc000abd020?, 0x69?, 0x70?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustSymlinkRelative({0xc014178080, 0x69}, {0xc015036930, 0x69})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs.go:294 +0x177
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).CreateSnapshot(0xc000085040, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:330 +0x5a5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage.RequestHandler({0xbdaab0?, 0xc01c35c040}, 0xc000298100)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:297 +0x5c5
main.requestHandler({0xbdaab0?, 0xc01c35c040}, 0xc000298100)
	github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:145 +0x286
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc002694390, {0xbdaab0?, 0xc01c35c040}, 0xc000298100, 0xb1faf8)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:344 +0xd8d
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xbdaab0?, 0xc01c35c040?}, 0xc000abd9b0?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:196 +0x37
net/http.HandlerFunc.ServeHTTP(0x946b60?, {0xbdaab0?, 0xc01c35c040?}, 0x4?)
	net/http/server.go:2122 +0x2f
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0xbda750, 0xc002d8e9a0}, 0x8e5a60?)
	github.com/klauspost/compress@v1.16.5/gzhttp/compress.go:484 +0x4f2
net/http.HandlerFunc.ServeHTTP(0x0?, {0xbda750?, 0xc002d8e9a0?}, 0x26a6b3?)
	net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc014880de0?}, {0xbda750, 0xc002d8e9a0}, 0xc000298100)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0123fc000, {0xbdabb8, 0xc014880d80})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

**Comment by tekert** [comment]
Uhmm, seems the local service can't create symlinks, we don't want to elevate pivileges to this service, I will check if i can enable symlink creation only and report back.
And also check why the logs banish the first time an error occurs. (something to do with stdout or stderror reseting)

**Comment by zekker6** [comment]
@tekert Glad to hear that works now, should we close this as resolved then?

**Comment by tekert** [comment]
Yes we could, the original problem was i could not create backups (was testing backup manager) but, now that this issue is resolved, another araises, (seems not related i could create a new issue) here are the logs:
```

Copyright 2018-2022 VictoriaMetrics, Inc - All Rights Reserved.
For any questions please contact info@victoriametrics.com
2023-07-24T09:54:04.610-0300    info    VictoriaMetrics/lib/logger/flag.go:12   build version: vmbackupmanager-20230602-121930-tags-v1.91.2-enterprise-0-g9c0ee3336
2023-07-24T09:54:04.615-0300    info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2023-07-24T09:54:04.615-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -dst="fs://E:\\Backups\\victoria-metrics-backups"
2023-07-24T09:54:04.615-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -eula="true"
2023-07-24T09:54:04.615-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -keepLastDaily="2"
2023-07-24T09:54:04.617-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -keepLastMonthly="3"
2023-07-24T09:54:04.618-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -keepLastWeekly="1"
2023-07-24T09:54:04.619-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -loggerTimezone="America/Argentina/Buenos_Aires"
2023-07-24T09:54:04.621-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -maxBytesPerSecond="10485760"
2023-07-24T09:54:04.622-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -snapshot.createURL="http://localhost:8428/snapshot/create"
2023-07-24T09:54:04.623-0300    info    VictoriaMetrics/lib/logger/flag.go:20     -storageDataPath="C:\\Monitoring\\victoria-metrics\\victoria-metrics-data"
2023-07-24T09:54:04.634-0300    info    VictoriaMetrics/lib/httpserver/httpserver.go:96 starting http server at http://127.0.0.1:8300/
2023-07-24T09:54:04.639-0300    info    VictoriaMetrics/lib/httpserver/httpserver.go:97 pprof handlers are exposed at http://127.0.0.1:8300/debug/pprof/
2023-07-24T09:54:04.655-0300    info    VictoriaMetrics/app/vmbackupmanager/main.go:363 sleeping for 5m56s before the next backup
2023-07-24T10:00:01.609-0300    info    VictoriaMetrics/lib/backup/actions/backup.go:116        starting backup from fslocal "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data/snapshots/20230724130001-1774CEFA8C6D71E5" to fsremote "E:\\Backups\\victoria-metrics-backups\\latest" using origin fsnil
2023-07-24T10:00:01.634-0300    panic   VictoriaMetrics/lib/backup/fslocal/fslocal.go:74        BUG: unexpected prefix for file "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\snapshots\\20230724130001-1774CEFA8C6D71E5\\data\\small\\2023_06\\176ED613C2B5507D\\index.bin"; want "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data/snapshots/20230724130001-1774CEFA8C6D71E5\\"
panic: BUG: unexpected prefix for file "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\snapshots\\20230724130001-1774CEFA8C6D71E5\\data\\small\\2023_06\\176ED613C2B5507D\\index.bin"; want "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data/snapshots/20230724130001-1774CEFA8C6D71E5\\"

goroutine 9 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x181362d, 0x5}, {0xc000312780, 0x124}, 0x2?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x181362d, 0x5}, {0x1844a5f?, 0x1628280?}, {0xc000013600?, 0x1628bc0?, 0xc000458220?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/fslocal.(*FS).ListParts(0x1?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/fslocal/fslocal.go:74 +0x2bd
github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/actions.runBackup(0xc000086140, {0x1a17b10?, 0xc000458170}, {0x1a0f890?, 0x214b5e0}, 0xc00052a029?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/actions/backup.go:118 +0x15e
github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/actions.(*Backup).Run(0xc00052a000?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/actions/backup.go:76 +0x1b4
main.(*backuper).makeBackup(0xc00006e0f0, 0xc000086140, {0x1816238?, 0xfffffcb9cf476000?})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmbackupmanager/main.go:496 +0x11e
main.(*backuper).run(0xc00006e0f0, {0x1a11da0, 0xc00006e0a0})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmbackupmanager/main.go:425 +0x20e
main.(*backuper).scheduleBackups(0xc00006e0f0, {0x1a11da0, 0xc00006e0a0})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmbackupmanager/main.go:372 +0x3a5
main.runBackupManager.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmbackupmanager/main.go:150 +0x65
created by main.runBackupManager
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmbackupmanager/main.go:148 +0x3aa

```

**Comment by zekker6** [comment]
@tekert Yes, please create a new issue for this one as it is related to another topic and it will be easier to track it with a separate issue.
