### ISSUE TITLE
Runtime panic during OpenTelemetry ingestion

### ISSUE THREAD

**Issue by JNKielmann** [VictoriaMetrics/VictoriaMetrics#4814]
### Describe the bug

We are trying out the new OpenTelemetry ingestion feature introduced in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2570. Metrics are send to Victoria Metrics via the [OTLP/HTTP Exporter of the OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter). This works fine most of the time but for some specific OpenTelemetry payloads it seems to cause an invalid memory access and crashes Victoria Metrics. From the stack trace it seems to be in the protobuf parser for Histogram data? 
We are running the single-node version of Victoria Metrics.

### To Reproduce

We see these crashes quite frequently (~1 crash every 10 minutes) but so far I was not able to pinpoint which exact metric is causing the issue and I was not able to craft a specific payload that always results in a crash. Are there any additional debug logs I could use to figure out what exactly Victoria Metrics was processing right before the crash? Let me know if there is any additional information I can provide.

### Version

victoria-metrics-20230727-221851-tags-v1.92.0-0-ge6a088b29b

### Logs

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 135 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:235 +0x65
panic({0xb315e0, 0x11b7e50})
	runtime/panic.go:890 +0x263
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).appendSamplesFromHistogram(0xc0005fa1b0, {0xc0009fcfa8, 0x14}, 0xc00027a370)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:137 +0x383
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).appendSamplesFromScopeMetrics(0xc000263100?, 0xc000443650?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:81 +0x25a
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).parseRequestToTss(0xc0005fa1b0, 0xe37ee0?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:273 +0x235
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.ParseStream({0x789b280cb1a0?, 0xc00064a500?}, 0x0, 0xc000647368)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:43 +0x2e9
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/opentelemetry.InsertHandler(0xc000263c00)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/opentelemetry/request_handler.go:26 +0xd9
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert.RequestHandler({0xe3b8b0, 0xc00010e8c0}, 0xc000263c00)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/main.go:216 +0x144b
main.requestHandler({0xe3b8b0?, 0xc00010e8c0}, 0xc000263c00)
	github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:128 +0x24a
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc000b12250, {0xe3b8b0?, 0xc00010e8c0}, 0xc000263c00, 0xd8f5e8)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:344 +0xd8d
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xe3b8b0?, 0xc00010e8c0?}, 0xc00367c700?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:196 +0x37
net/http.HandlerFunc.ServeHTTP(0x11ba660?, {0xe3b8b0?, 0xc00010e8c0?}, 0x4?)
	net/http/server.go:2122 +0x2f
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0xe3b790, 0xc00367c700}, 0xc000647ad0?)
	github.com/klauspost/compress@v1.16.7/gzhttp/compress.go:486 +0x35a
net/http.HandlerFunc.ServeHTTP(0x0?, {0xe3b790?, 0xc00367c700?}, 0x67bd34?)
	net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xe3a878?}, {0xe3b790, 0xc00367c700}, 0xc000263c00)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000184480, {0xe3bbf8, 0xc00059e7b0})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

### Used command-line flags

--retentionPeriod=3
--storageDataPath=/storage
--envflag.enable=true
--envflag.prefix=VM_
--loggerFormat=json
--usePromCompatibleNaming=true

**Comment by DaveWK** [comment]
Also seeing this on `vminsert-20230728-102617-tags-v1.92.1-cluster-0-gc5c539f97`

```
{"ts":"2023-08-10T19:31:18.554Z","level":"info","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:268","msg":"successfully dialed -storageNode=\"victoria-metrics-victoria-metrics-cluster-vmstorage-1.victoria-metrics-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400\""}
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 157 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:235 +0x65
panic({0x8ab9e0, 0xc46d30})
        runtime/panic.go:890 +0x263
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).appendSamplesFromHistogram(0xc0014da360, {0xc000fc8f40, 0x38}, 0xc000e61130)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:137 +0x383
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).appendSamplesFromScopeMetrics(0xc002ade000?, 0xc002ad9d70?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:81 +0x25a
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.(*writeContext).parseRequestToTss(0xc0014da360, 0xa1e5e0?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:273 +0x235
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream.ParseStream({0x7fd73284bba8?, 0xc002af2440?}, 0x1, 0xc00039f550)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:43 +0x2e9
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/opentelemetry.InsertHandler(0x0, 0xc0007df200)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/opentelemetry/request_handler.go:30 +0xfa
main.requestHandler({0xa20e10, 0xc000270280}, 0xc0007df200)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/main.go:295 +0x1005
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc0003093f0, {0xa20e10?, 0xc000270280}, 0xc0007df200, 0x9b4ea0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:344 +0xd8d
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xa20e10?, 0xc000270280?}, 0xc00033a380?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:196 +0x37
net/http.HandlerFunc.ServeHTTP(0x902700?, {0xa20e10?, 0xc000270280?}, 0x4?)
        net/http/server.go:2122 +0x2f
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0xa20d20, 0xc00033a380}, 0xc00039fad0?)
        github.com/klauspost/compress@v1.16.7/gzhttp/compress.go:486 +0x35a
net/http.HandlerFunc.ServeHTTP(0x0?, {0xa20d20?, 0xc00033a380?}, 0x6556f4?)
        net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xa20100?}, {0xa20d20, 0xc00033a380}, 0xc0007df200)
        net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0014da120, {0xa21098, 0xc00073ba40})
        net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        net/http/server.go:3089 +0x5ed
```

**Comment by f41gh7** [comment]
@DaveWK  can you test fix with following docker image `docker.io/victoriametrics/vmagent:heads-open-telemetry-fixes-0-g147c49887`.

 Opentelemetry Historgram was incorrectly converted, missing `sum` field caused runtime panic. Opentelemetry specification allows non-counter buckets.

 This fix converts Historgram as gauge - original metric name concated with `_count` suffix. Bucket values dropped, since it cannot be properly used with `historgram` functions from metricsql.

**Comment by f41gh7** [comment]
> @f41gh7 thanks, but the crash loop is happening on `vminsert` not `vmagent` -- do I need a `vminsert` docker image?

 Ah, in this case you have to wait for the next release. This bugfix must be back-ported to the cluster branch at first.

**Comment by valyala** [comment]
VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent.html) shouldn't panic when importing unsupported Opentelemetry histogram types with non-counter buckets starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
