### ISSUE TITLE
Crash and data loss after background operation

### ISSUE THREAD

**Issue by a-bali** [VictoriaMetrics/VictoriaMetrics#5030]
### Describe the bug

Today I run into an issue where Victoriametrics started some background operation at 6am (I was not able to find out based on what timer, I'm running the Docker image on Linux), consumed a lot of resources (see attached snapshot from the official Grafana dashboard) and generated tens of thousands of log entries over a timespan of more than 2 hours and finally crashed. As a result, I also lost some data i.e. some timeseries show data only after it was restarted after the crash. All relevant logs are included below, incl. some warning messages after the restart.

Any ideas what might have caused this?

### To Reproduce

Couldn't reproduce so far.

### Version

victoria-metrics-20230812-215739-tags-v1.93.0-0-g59f7d810c9

### Logs

```
Sep 20 06:00:00 nas victoriametrics[685]: 2023-09-20T04:00:00.825Z        info        VictoriaMetrics/lib/storage/index_db.go:305        dropping indexDB "/storage/indexdb/177DB5A24E4B3B9D"
Sep 20 06:00:00 nas victoriametrics[685]: 2023-09-20T04:00:00.844Z        info        VictoriaMetrics/lib/storage/index_db.go:307        indexDB "/storage/indexdb/177DB5A24E4B3B9D" has been dropped
Sep 20 06:00:00 nas victoriametrics[685]: 2023-09-20T04:00:00.874Z        info        VictoriaMetrics/lib/storage/index_db.go:305        dropping indexDB "/storage/indexdb/177DB5A24E4B3B9E"
Sep 20 06:00:00 nas victoriametrics[685]: 2023-09-20T04:00:00.940Z        info        VictoriaMetrics/lib/storage/index_db.go:307        indexDB "/storage/indexdb/177DB5A24E4B3B9E" has been dropped
Sep 20 06:00:01 nas victoriametrics[685]: 2023-09-20T04:00:01.021Z        info        VictoriaMetrics/lib/storage/index_db.go:305        dropping indexDB "/storage/indexdb/177DB5A24E4B3B9F"
Sep 20 06:00:01 nas victoriametrics[685]: 2023-09-20T04:00:01.058Z        info        VictoriaMetrics/lib/storage/index_db.go:307        indexDB "/storage/indexdb/177DB5A24E4B3B9F" has been dropped
[thousands of such lines over more than 2 hours skipped]
Sep 20 08:23:42 nas victoriametrics[685]: 2023-09-20T06:23:42.846Z        info        VictoriaMetrics/lib/storage/index_db.go:307        indexDB "/storage/indexdb/17841A8D7AA6E2E2" has been dropped
Sep 20 08:23:42 nas victoriametrics[685]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 20 08:23:42 nas victoriametrics[685]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x7d30c9]
Sep 20 08:23:42 nas victoriametrics[685]:
Sep 20 08:23:42 nas victoriametrics[685]: goroutine 147 [running]:
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).getDeletedMetricIDs(...)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:300
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getTSIDByMetricNameNoExtDB(0xc000cfe120, 0xc00085b520, {0xc000d46980, 0x7a, 0xc0007e66c0?}, 0x4ca4)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:1789 +0x49
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexSearch).getTSIDByMetricName(0xc000cfe120, 0xc00085b520, {0xc000d46980, 0x7a, 0x80}, 0x4ca4)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:449 +0x49
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).add(0xc00021eb60, {0xc006258000, 0x1f40, 0x1f40}, {0xc000a66000, 0x1f40, 0x1f40}, {0xc006678000, 0x11d4, 0x1266}, ...)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:1829 +0xe10
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).AddRows(0x126e610?, {0xc006678000, 0x11d4, 0x1266}, 0x0?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:1555 +0x165
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage.AddRows({0xc006678000, 0x11d4, 0x1266})
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:150 +0x8e
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/common.(*InsertCtx).FlushBufs(0xc000942680)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/common/insert_ctx.go:158 +0x169
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/prompush.push(0xc000942680, {0xc004be2000, 0x11d4, 0x4a8?})
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/prompush/push.go:79 +0x1b2
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/prompush.Push(0xc000b1df30)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/prompush/push.go:41 +0x7c
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert.Init.func1(0xc0057462a0?, 0xbcd28b?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/main.go:99 +0x16
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).pushData(0xc0005e77a0, 0xc00085bb48?, 0xc0073044d8?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:534 +0x4c
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).processScrapedData(0xc0005e77a0, 0x0?, 0x18ab14239ac, 0xc003bebe60, {0x0, 0x0})
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:510 +0x4eb
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).scrapeInternal(0xc0005e77a0, 0xffffffffffffffff?, 0xffffffffffffffff?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:440 +0xfe
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).scrapeAndLogError(0xc0005e77a0, 0xc005415de8?, 0x18ab14239ac)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:371 +0x2f
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).run(0xc0005e77a0, 0xc0002cec00, 0x0?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:357 +0x5b7
Sep 20 08:23:42 nas victoriametrics[685]: github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scraperGroup).update.func1(0x0?)
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:418 +0x91
Sep 20 08:23:42 nas victoriametrics[685]: created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scraperGroup).update in goroutine 145
Sep 20 08:23:42 nas victoriametrics[685]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:413 +0x849
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.972Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: victoria-metrics-20230812-215739-tags-v1.93.0-0-g59f7d810c9
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:13        command-line flags
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -httpListenAddr=":8428"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -opentsdbListenAddr=":4242"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -promscrape.config="/prometheus.yml"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -retentionPeriod="30d"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -selfScrapeInterval="10s"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/lib/logger/flag.go:20          -storageDataPath="/storage"
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/app/victoria-metrics/main.go:70        starting VictoriaMetrics at ":8428"...
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.976Z        info        VictoriaMetrics/app/vmstorage/main.go:108        opening storage at "/storage" with -retentionPeriod=30d
Sep 20 08:23:45 nas victoriametrics[685]: 2023-09-20T06:23:45.998Z        info        VictoriaMetrics/lib/memory/memory.go:42        limiting caches to 2291739033 bytes, leaving 1527826023 bytes to the OS according to -memory.allowedPercent=60
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.485Z        info        VictoriaMetrics/lib/storage/storage.go:935        discarding /storage/cache/curr_hour_metric_ids, since it contains outdated hour; got 470696; want 470886
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.487Z        info        VictoriaMetrics/lib/storage/storage.go:935        discarding /storage/cache/prev_hour_metric_ids, since it contains outdated hour; got 470695; want 470885
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.499Z        info        VictoriaMetrics/lib/storage/storage.go:2536        removing obsolete indexdb dir "/storage/indexdb/17841A8D7AA6E2E3"...
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.506Z        info        VictoriaMetrics/lib/storage/storage.go:2538        removed obsolete indexdb dir "/storage/indexdb/17841A8D7AA6E2E3"
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.540Z        info        VictoriaMetrics/lib/storage/storage.go:891        discarding /storage/cache/next_day_metric_ids_v2, since it contains data for stale generation; got 1692708743664057246; want 1694508554748617445
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.540Z        info        VictoriaMetrics/lib/storage/storage.go:896        discarding /storage/cache/next_day_metric_ids_v2, since it contains data for stale date; got 19612; want 19620
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.729Z        info        VictoriaMetrics/app/vmstorage/main.go:122        successfully opened storage "/storage" in 0.753 seconds; partsCount: 51; blocksCount: 1119465; rowsCount: 5313728326; sizeBytes: 2937642643
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.735Z        info        VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:114        loading rollupResult cache from "/storage/cache/rollupResult"...
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.885Z        info        VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:142        loaded rollupResult cache from "/storage/cache/rollupResult" in 0.150 seconds; entriesCount: 381, sizeBytes: 17367040
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.885Z        info        VictoriaMetrics/lib/ingestserver/opentsdb/server.go:48        starting TCP OpenTSDB collector at ":4242"
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.886Z        info        VictoriaMetrics/lib/ingestserver/opentsdb/server.go:58        starting UDP OpenTSDB collector at ":4242"
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.886Z        info        VictoriaMetrics/app/victoria-metrics/main.go:80        started VictoriaMetrics in 0.911 seconds
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.887Z        info        VictoriaMetrics/app/victoria-metrics/self_scraper.go:45        started self-scraping `/metrics` page with interval 10.000 seconds
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.887Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:96        starting http server at http://127.0.0.1:8428/
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.887Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:97        pprof handlers are exposed at http://127.0.0.1:8428/debug/pprof/
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.888Z        info        VictoriaMetrics/lib/promscrape/scraper.go:113        reading Prometheus configs from "/prometheus.yml"
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.908Z        info        VictoriaMetrics/lib/promscrape/config.go:122        starting service discovery routines...
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.908Z        info        VictoriaMetrics/lib/promscrape/config.go:128        started service discovery routines in 0.000 seconds
Sep 20 08:23:46 nas victoriametrics[685]: 2023-09-20T06:23:46.912Z        info        VictoriaMetrics/lib/promscrape/scraper.go:430        static_configs: added targets: 2, removed targets: 0; total targets: 2
Sep 20 09:07:46 nas victoriametrics[685]: 2023-09-20T07:07:46.854Z        info        VictoriaMetrics/app/vmselect/querystats/querystats.go:68        enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
```

### Screenshots

![grafana2 nas_d_wNf0q_kZk_victoriametrics_orgId=1 from=now-6h to=now](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/6281927/52112c7e-094a-4a59-9257-91d15386fdad)

**Comment by liyuanchuan8** [comment]
# I have the same problem，some data lost
## version：v1.93.0-cluster
```
{"ts":"2023-09-20T04:10:44.038Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (13 parts, 3751846 items, 15333 blocks, 175723370 bytes)
into (1 part, 2520079 items, 11316 blocks, 100907964 bytes) in 147.126 seconds at 25500 items/sec to \"/storage/indexdb/177D91FD2599D08A/17867F86C463F7A4\""}
{"ts":"2023-09-20T04:10:46.401Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (12 parts, 3928683 items, 14849 blocks, 166278016 bytes)
into (1 part, 2863433 items, 11613 blocks, 110358528 bytes) in 119.129 seconds at 32978 items/sec to \"\""}
{"ts":"2023-09-20T04:10:48.528Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (15 parts, 4103928 items, 15527 blocks, 178836976 bytes)
into (1 part, 2901101 items, 12042 blocks, 111230976 bytes) in 138.976 seconds at 29529 items/sec to \"\""}
{"ts":"2023-09-20T04:10:50.033Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (15 parts, 4176737 items, 15721 blocks, 180642960 bytes)
into (1 part, 2961826 items, 12161 blocks, 111091712 bytes) in 127.867 seconds at 32664 items/sec to \"\""}
{"ts":"2023-09-20T04:10:57.892Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (5 parts, 6987668 items, 32109 blocks, 276956416 bytes) i
nto (1 part, 6316699 items, 28336 blocks, 254661100 bytes) in 370.450 seconds at 18862 items/sec to \"/storage/indexdb/177D91FD2599D082/17867F6981C2A2FB\""}
{"ts":"2023-09-20T04:10:59.461Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (6 parts, 2213806 items, 10324 blocks, 93663760 bytes) in
to (1 part, 2179410 items, 8911 blocks, 87762322 bytes) in 45.454 seconds at 48704 items/sec to \"/storage/indexdb/177D91FD2599D08A/17867F86C463FC9A\""}
{"ts":"2023-09-20T04:11:03.968Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (14 parts, 4472560 items, 18771 blocks, 198529904 bytes)
into (1 part, 2920820 items, 13973 blocks, 137953280 bytes) in 265.872 seconds at 16822 items/sec to \"\""}
{"ts":"2023-09-20T04:11:04.415Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (15 parts, 4604131 items, 19493 blocks, 199072448 bytes)
into (1 part, 3130804 items, 14524 blocks, 139173888 bytes) in 246.168 seconds at 18703 items/sec to \"\""}
{"ts":"2023-09-20T04:11:05.256Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (15 parts, 4583174 items, 18914 blocks, 209562336 bytes)
into (1 part, 3103777 items, 14035 blocks, 137947776 bytes) in 187.785 seconds at 24406 items/sec to \"\""}
{"ts":"2023-09-20T04:11:06.246Z","level":"info","caller":"VictoriaMetrics/lib/storage/index_db.go:305","msg":"dropping indexDB \"/storage/indexdb/177D91FD2599D082\""}
{"ts":"2023-09-20T04:11:06.380Z","level":"info","caller":"VictoriaMetrics/lib/mergeset/table.go:1126","msg":"merged (15 parts, 4877462 items, 20021 blocks, 216619312 bytes) 
into (1 part, 3172616 items, 14900 blocks, 137969664 bytes) in 210.063 seconds at 23219 items/sec to \"\""}
{"ts":"2023-09-20T04:11:06.667Z","level":"info","caller":"VictoriaMetrics/lib/storage/index_db.go:307","msg":"indexDB \"/storage/indexdb/177D91FD2599D082\" has been dropped"
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f84a1]

goroutine 17356104 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).SetBig(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:451
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).putMetricIDsToTagFiltersCache(0xc003820160, 0x90af72?, {0xc09557c1c0, 0x1b, 0x1b}, {0xc024b49600, 0x1dd, 0x
200})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:337 +0x201
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).searchMetricIDs(0xc003820160, 0x8fc0a2?, {0xc0001a6138, 0x1, 0x1}, {0x18ab0b96658, 0x18ab0bf1f30}, 0x493e0,
 0x650a6e82)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:1812 +0x879
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Search).Init(0xc064ed2300, 0xc154be0040?, 0xc00019b520, {0xc0001a6138?, 0x1, 0x1}, {0x18ab0b96658, 0x18ab0bf1f30}, 0
x1d8?, 0x650a6e82)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/search.go:195 +0x2f5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers.(*vmstorageAPI).InitSearch(0xc000afd820, 0xc154be0000?, 0xc154be0040, 0x0?)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers/vmselect.go:72 +0x17b
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processSearch(0xc000264640, 0xc154be0000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:1026 +0x117
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processRPC(0xc154be0000?, 0x8ed758972cdef?, {0xc0deaf4cf0, 0x9})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:561 +0x6b
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processRequest(0xc1112ea000?, 0xc154be0000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:513 +0x45f
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processConn(0xa00270?, 0xc08640e8a0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:255 +0xbd
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).run.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:212 +0x228
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).run in goroutine 967
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:180 +0x24a
```
# grafana display
<img width="1844" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/18182080/34c64ecb-224a-49f3-9a00-0cba051eb663">

**Comment by liyuanchuan8** [comment]
## Parameters are as follows
```
          args:
            - --retentionPeriod=60d
            - --storageDataPath=/storage
            - --memory.allowedPercent=80
            - --maxConcurrentInserts=20
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
```

**Comment by a-bali** [comment]
The issue (mine at least) might be related to #4873. Also please see attached some anomaly in `vm_next_retention_seconds`. I will upgrade to 1.93.1 and see if the problem occurs again, but I would appreciate if someone could confirm based on the above information that this seems to be the issue. 
![Screenshot 2023-09-21 at 9 50 37](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/6281927/7a96edd3-1325-4940-8477-50e5542cf4aa)

**Comment by zekker6** [comment]
@a-bali @liyuanchuan8 Yes, this is exactly the same as issue in #4873 
This issue is caused by a bug introduced in [v1.93.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.0), so it is recommended to restore data from the backup and update to [v1.93.5 ](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.5)as soon as possible.

**Comment by liyuanchuan8** [comment]
@zekker6 Thanks！It has been updated to [v1.93.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.0) today

**Comment by hagen1778** [comment]
@zekker6 @liyuanchuan8 can this issue be closed?

**Comment by zekker6** [comment]
Seems to me like it was fixed in v1.93.5 and we can close this one.

**Comment by a-bali** [comment]
I do confirm that I haven't encountered this since I upgraded to v1.93.5. Thank you.
