### ISSUE TITLE
vmstorage panic when cannot obtain partition time rage from smallPartsPath 

### ISSUE THREAD

**Issue by jingb** [VictoriaMetrics/VictoriaMetrics#5033]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

vmstorage panic and it prints 
```
FATAL: cannot obtain partition time range from smallPartsPath /home/service/var/data2/vmstorage/data/small/.Trash/
cannot parse partition name ".Trash": parsing time ".Trash" as "2006_01"
```

there are a file named parts.json in .Trash.
and its content is 
```
{"Small":[],"Big":[]}
```

vmstorage-prod -version 
vmstorage-20230812-132325-tags-v1.93.0-cluster-0-g9ac0d980f9

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by jingb** [comment]
full log message 
```
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: vmstorage-20230812-132325-tags-v1.93.0-cluster-0-g9ac0d980f9
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/lib/logger/flag.go:20     -dedup.minScrapeInterval="10s"
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/lib/logger/flag.go:20     -retentionPeriod="90d"
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/lib/logger/flag.go:20     -storageDataPath="/home/service/var/data2/vmstorage"
2023-09-21T06:48:31.482Z        info    VictoriaMetrics/app/vmstorage/main.go:100       opening storage at "/home/service/var/data2/vmstorage" with -retentionPeriod=90d
2023-09-21T06:48:31.483Z        info    VictoriaMetrics/lib/memory/memory.go:42 limiting caches to 80808512716 bytes, leaving 53872341812 bytes to the OS according to -memo
ry.allowedPercent=60
2023-09-21T06:48:31.573Z        info    VictoriaMetrics/lib/storage/storage.go:950      discarding /home/service/var/data2/vmstorage/cache/curr_hour_metric_ids, since it co
ntains outdated hour; got 470891; want 470910
2023-09-21T06:48:31.573Z        info    VictoriaMetrics/lib/storage/storage.go:950      discarding /home/service/var/data2/vmstorage/cache/prev_hour_metric_ids, since it co
ntains outdated hour; got 470890; want 470909
2023-09-21T06:48:31.595Z        info    VictoriaMetrics/lib/storage/storage.go:911      discarding /home/service/var/data2/vmstorage/cache/next_day_metric_ids_v2, since it 
contains data for stale date; got 19620; want 19621
2023-09-21T06:48:34.037Z        panic   VictoriaMetrics/lib/storage/partition.go:282    FATAL: cannot obtain partition time range from smallPartsPath "/home/service/var/dat
a2/vmstorage/data/small/.Trash": cannot parse partition name ".Trash": parsing time ".Trash" as "2006_01": cannot parse ".Trash" as "2006"
panic: FATAL: cannot obtain partition time range from smallPartsPath "/home/service/var/data2/vmstorage/data/small/.Trash": cannot parse partition name ".Trash": pars
ing time ".Trash" as "2006_01": cannot parse ".Trash" as "2006"

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x8e5642, 0x5}, {0xc000207340, 0xde}, 0x2?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa91
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x8e5642, 0x5}, {0x90660a?, 0xc00001c5c0?}, {0xc000217218?, 0xc0001b2680?, 0xc00001c5c0?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x194
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenPartition({0xc00001c580?, 0xc0002172c0?}, {0xc00001c5c0, 0x31}, 0x8de7c0?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:282 +0x4e5
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenPartitions({0xc0001324b0, 0x2c}, {0xc0001326f0, 0x2a}, 0x0?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:480 +0x275
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenTable({0xc000132360?, 0x17867c290316d381?}, 0xc0001b2680)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:103 +0x269
```

**Comment by zekker6** [comment]
Hello @jingb 

This error means that vmstorage did not expect to find a directory with `.Trash` name at `/home/service/var/data2/vmstorage/data/small/.Trash`.
vmstorage expects that `-storageDataPath` folder cannot be modified by any other process, so that there will be no additional files or directories created. Once vmstorage finds directory or file which is not known it will fail with an error.

**Comment by jingb** [comment]
@zekker6 
thanks.
this directory is created by the other process in big directory. and it seems it will be copied into the small directory
