### ISSUE TITLE
Snap `vmagent` tries to save to invalid folder

### ISSUE THREAD

**Issue by Foorack** [VictoriaMetrics/VictoriaMetrics#5251]
### Describe the bug

When trying to use vmagent snap, it tries to write to a invalid location.

```
# cat /var/snap/vmagent/current/extra_flags 
FLAGS="--httpListenAddr=127.0.0.1:8429 --remoteWrite.url=http://127.0.0.1:8428/api/v1/write"
```

### To Reproduce

1. snap install vmagent
2. follow VMAgent minimal setup guide
3. It will try to write to a non-existing folder it does not have rights to edit

### Version

vmagent                    v1.94.0           9      latest/stable    denisgolius  -

### Logs

```
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/logger/flag.go:13	command-line flags
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/logger/flag.go:20	  -httpListenAddr="127.0.0.1:8429"
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/logger/flag.go:20	  -promscrape.config="/etc/vmagent-scrape-config.yaml"
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/logger/flag.go:20	  -remoteWrite.tmpDataPath="/var/lib/vmagent-remotewrite-data"
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/logger/flag.go:20	  -remoteWrite.url="secret"
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/app/vmagent/main.go:121	starting vmagent at "127.0.0.1:8429"...
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	info	/builder/parts/build/build/lib/memory/memory.go:42	limiting caches to 2458438041 bytes, leaving 1638958695 bytes to the OS according to -memory.allowedPercent=60
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 2023-10-30T16:24:44.059Z	panic	/builder/parts/build/build/lib/fs/fs.go:117	FATAL: cannot create directory: mkdir /var/lib/vmagent-remotewrite-data: permission denied
2023-10-30T16:24:44Z vmagent.vmagent[19460]: panic: FATAL: cannot create directory: mkdir /var/lib/vmagent-remotewrite-data: permission denied
2023-10-30T16:24:44Z vmagent.vmagent[19460]: goroutine 1 [running]:
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xab6171, 0x5}, {0xc00002c0c0, 0x5a}, 0x1?)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/logger/logger.go:309 +0xa91
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xab6171, 0x5}, {0xacc8f0?, 0xc2bd00?}, {0xc000227280?, 0xc00022b740?, 0x71?})
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/logger/logger.go:138 +0x199
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/logger/logger.go:130
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/logger/logger.go:126
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.mustMkdirSync({0xc0001c0280, 0x45})
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/fs/fs.go:117 +0x6f
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustMkdirIfNotExist({0xc0001c0280, 0x45})
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/fs/fs.go:102 +0x39
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.tryOpeningQueue({0xc0001c0280, 0x45}, {0xc0000145b0, 0xc}, 0x20000080, 0x2000000, 0x0)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/persistentqueue/persistentqueue.go:173 +0x537
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.mustOpenInternal({0xc0001c0280, 0x45}, {0xc0000145b0, 0xc}, 0x20000080, 0x2000000, 0x2?)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/persistentqueue/persistentqueue.go:136 +0x1b8
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.mustOpen(...)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/persistentqueue/persistentqueue.go:126
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/lib/persistentqueue.MustOpenFastQueue({0xc0001c0280, 0x45}, {0xc0000145b0?, 0x2?}, 0x2?, 0x4d91ba?)
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/lib/persistentqueue/fastqueue.go:46 +0x57
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newRemoteWriteCtx(0x0, 0xc0001ca000, 0xc000227bc0?, {0xc0000145b0, 0xc})
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/app/vmagent/remotewrite/remotewrite.go:575 +0x2eb
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.newRemoteWriteCtxs(0x0, {0xc00009a1e0, 0x1, 0xc000227ee0?})
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/app/vmagent/remotewrite/remotewrite.go:261 +0x52e
2023-10-30T16:24:44Z vmagent.vmagent[19460]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.Init()
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/app/vmagent/remotewrite/remotewrite.go:171 +0x2c9
2023-10-30T16:24:44Z vmagent.vmagent[19460]: main.main()
2023-10-30T16:24:44Z vmagent.vmagent[19460]: 	/builder/parts/build/build/app/vmagent/main.go:123 +0x3ab
2023-10-30T16:24:44Z systemd[1]: snap.vmagent.vmagent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2023-10-30T16:24:44Z systemd[1]: snap.vmagent.vmagent.service: Failed with result 'exit-code'.
```

**Comment by Foorack** [comment]
I just received Rev 12 and there is now a folder `/var/lib/vmagent`. I haven't verified if it will save there by default, but that folder was not there in Rev 9.

**Comment by Foorack** [comment]
@denisgolius  Not immediately related to the issue topic, but I don't remember seeing this after the latest patch:

> 2023-11-15T10:52:00Z vmagent.vmagent[1889409]: /snap/vmagent/13/bin/vmagent-wrapper: 1: /snap/vmagent/13/bin/vmagent-wrapper: !/bin/sh: not found
2023-11-15T10:52:00Z vmagent.vmagent[1889410]: cp: cannot stat '/snap/vmagent/13/etc/vmagent-scrape-config.yaml': No such file or directory

Specifically the "!/bin/sh: not found" is slightly concerning.


However, it **does** seem like vmagnet snap is correctly using `/var/lib/vmagent` folder now.

**Comment by denisgolius** [comment]
> @denisgolius Not immediately related to the issue topic, but I don't remember seeing this after the latest patch:
> 
> > 2023-11-15T10:52:00Z vmagent.vmagent[1889409]: /snap/vmagent/13/bin/vmagent-wrapper: 1: /snap/vmagent/13/bin/vmagent-wrapper: !/bin/sh: not found
> > 2023-11-15T10:52:00Z vmagent.vmagent[1889410]: cp: cannot stat '/snap/vmagent/13/etc/vmagent-scrape-config.yaml': No such file or directory
> 
> Specifically the "!/bin/sh: not found" is slightly concerning.
> 
> However, it **does** seem like vmagnet snap is correctly using `/var/lib/vmagent` folder now.

Could you please share your OS name and version?

**Comment by denisgolius** [comment]
Closing this issue due to lack of activity. Please feel free to reopen it if your issue will appears once again.
