### ISSUE TITLE
newrelic: vminsert panics when ingesting newrelic batch to a tenant

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5416]
### Describe the bug

See this thread https://victoriametrics.slack.com/archives/CGZF1H6L9/p1701467406431099 

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 9 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
        /Users/hagen/PhpstormProjects/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:240 +0x58
panic({0x10095c7a0?, 0x100c587d0?})
        /usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/netstorage.(*InsertCtx).WriteDataPoint(0x140001281b0, 0x0, {0x140001f4480, 0x7, 0x8}, 0x0?, 0x0?)
        /Users/hagen/PhpstormProjects/VictoriaMetrics/VictoriaMetrics/app/vminsert/netstorage/insert_ctx.go:122 +0x3c
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/newrelic.insertRows({0x140000b89a0, 0x2, 0x100742a20?}, {0x0, 0x0, 0x140001272b0?})
        /Users/hagen/PhpstormProjects/VictoriaMetrics/VictoriaMetrics/app/vminsert/newrelic/request_handler.go:65 +0x3c4
github.com/VictoriaMetrics/VictoriaMetrics/app/vminsert/newrelic.InsertHandlerForHTTP.func1({0x140000b89a0?, 0x1400013e000?, 0x23a?})
        /Users/hagen/PhpstormProjects/VictoriaMetrics/VictoriaMetrics/app/vminsert/newrelic/request_handler.go:30 +0x2c

```

### To Reproduce

```
 curl -X POST -H 'Content-Type: application/json' --data-binary @export.json ht
tp://localhost:8480/insert/0/newrelic/infra/v2/metrics/events/bulk

```

### Version

v1.95.1

**Comment by valyala** [comment]
The bugfix has been included in [the release v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
