### ISSUE TITLE
Migrating data from victorialogs-single to cluster version 

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5722]
### Is your question request related to a specific component?

Victorialogs

### Describe the question in detail

Once the clustered version of Victorialogs is released, I assume there will be a process that will allow users to easily migrate their data from the single-node version to the clustered version?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
Yes, data in Victorialogs single is intentionally designed to be compatible with cluster version, so there will be a easy way to migrate the data.

**Comment by IsQiao** [comment]
No, the single-node data is not in the same format as the cluster version.

``` shell
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmstorage-20240425-150523-tags-v1.101.0-cluster-0-g310d100ed
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="14s"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="93d"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxConcurrentRequests="8"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueueDuration="20s"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="300000000"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/home/orion/vmdata"
2024-07-30T02:45:49.579Z	info	VictoriaMetrics/app/vmstorage/main.go:101	opening storage at "/home/orion/vmdata" with -retentionPeriod=93d
2024-07-30T02:45:49.581Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 10091097292 bytes, leaving 6727398196 bytes to the OS according to -memory.allowedPercent=60
2024-07-30T02:45:49.593Z	info	VictoriaMetrics/lib/storage/storage.go:982	discarding /home/orion/vmdata/cache/curr_hour_metric_ids, since it contains outdated hour; got 478164; want 478418
2024-07-30T02:45:49.593Z	info	VictoriaMetrics/lib/storage/storage.go:982	discarding /home/orion/vmdata/cache/prev_hour_metric_ids, since it contains outdated hour; got 478163; want 478417
2024-07-30T02:45:49.601Z	info	VictoriaMetrics/lib/storage/storage.go:943	discarding /home/orion/vmdata/cache/next_day_metric_ids_v2, since it contains data for stale date; got 19923; want 19934
2024-07-30T02:45:49.606Z	panic	VictoriaMetrics/lib/storage/part.go:82	FATAL: cannot unmarshal metaindex data from "/home/orion/vmdata/data/small/2024_07/17E486B8DB13163F": cannot unmarshal metaindexRow #1 from metaindex data: too big IndexBlockSize; got 3406264495; cannot exceed 131072
panic: FATAL: cannot unmarshal metaindex data from "/home/orion/vmdata/data/small/2024_07/17E486B8DB13163F": cannot unmarshal metaindexRow #1 from metaindex data: too big IndexBlockSize; got 3406264495; cannot exceed 131072

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x9090a9, 0x5}, {0xc00025e000, 0xd8}, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:301 +0xa74
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x9090a9, 0x5}, {0x92434c?, 0xc0006e6e10?}, {0xc000034bb0?, 0x0?, 0xa30450?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:141 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:133
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:129
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.newPart(0xc00001fc80, {0xc00058ff80, 0x36}, 0x42fb4c, {0xa2ebc0, 0xc0006e6e10}, {0xa2ebf0, 0xc00029b5c0}, {0xa2ebf0, 0xc00029b600}, ...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:82 +0x13b
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenFilePart({0xc00058ff80?, 0x25?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:72 +0x3d9
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenParts({0xc00001f980, 0x30}, {0xc00001f920, 0x25}, {0xc0000fe400, 0x20, 0x2?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1954 +0x698
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenPartition({0xc00001f920?, 0xc0000352d0?}, {0xc00001f950, 0x23}, 0xc0000db880)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:252 +0x2b7
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenPartitions({0xc00019e0c0, 0x1d}, {0xc00019e220, 0x1b}, 0xc0000db880)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:513 +0x275
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenTable({0xc000026288?, 0xc0004642a0?}, 0xc0000db880)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/table.go:103 +0x269
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.MustOpenStorage({0x7ffef944e5db?, 0x908da7?}, 0x1c8bf8c9b30000, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:290 +0xf85
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:103 +0x405
```

**Comment by jiekun** [comment]
> No, the single-node data is not in the same format as the cluster version.

Hi @IsQiao . May I confirm if those logs are from VictoriaMetrics Single Node/Cluster? This issue aims to discuss about [VictoriaLogs](https://victoriametrics.com/products/victorialogs/)

**Comment by IsQiao** [comment]
> > No, the single-node data is not in the same format as the cluster version.
> 
> Hi @IsQiao . May I confirm if those logs are from VictoriaMetrics Single Node/Cluster? This issue aims to discuss about [VictoriaLogs](https://victoriametrics.com/products/victorialogs/)

Sorry, I read it wrong.
