### ISSUE TITLE
vmstorage has a bug that causes the program to crash：cannot parse simplified regexp "object(?:(?:)

### ISSUE THREAD

**Issue by Joechengli** [VictoriaMetrics/VictoriaMetrics#6383]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

The detailed log is as follows：
![error](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37071875/08df5971-d744-4eef-9685-216065d6a7bf)
goroutine 149 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/regexutil.simplifyRegexp(0xc000de9810, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/regexutil/regexutil.go:194 +0x155
github.com/VictoriaMetrics/VictoriaMetrics/lib/regexutil.Simplify({0xc000c3f500, 0x3259})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/regexutil/regexutil.go:149 +0x37
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.simplifyRegexp({0xc0013a8a00, 0x3259})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/tag_filters.go:898 +0xc6
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*tagFilter).Init(0xc000fd4208, {0xc000014ee0, 0x9, 0x7f18119dae18?}, {0xc0000e4310, 0x6, 0x10}, {0xc0013a5500, 0x3259, 0x3500}, ...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/tag_filters.go:463 +0x34a
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*TagFilters).Add(0xc0011d2180, {0xc0000e4310, 0x6, 0x10}, {0xc0013a5500?, 0x18fb75c7180?, 0xc000a53a80?}, 0xfb?, 0xe8?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/tag_filters.go:212 +0x2c6
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers.(*vmstorageAPI).setupTfss(0xc000688190, 0x0, 0xc0011c0340, {0xc000a53bb8?, 0x7adba5?}, 0x493e0, 0x66583e14)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers/vmselect.go:189 +0x4e8
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers.(*vmstorageAPI).InitSearch(0xc000688190, 0x0, 0xc0011c0340, 0x66583e14)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/servers/vmselect.go:66 +0xc8
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processSearch(0xc000148640, 0xc0011c0300)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:1034 +0x11d
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processRPC(0xc000148640, 0xc0011c0300, {0xc000014ec0, 0x9})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:562 +0x6b
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processRequest(0xc000148640, 0xc0011c0300)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:514 +0x465
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).processConn(0xc000148640, 0xc0001c1a40)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:255 +0xac
github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).run.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:212 +0x228
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi.(*Server).run in goroutine 208
        github.com/VictoriaMetrics/VictoriaMetrics/lib/vmselectapi/server.go:180 +0x188

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @Joechengli 
which VM version is it?

**Comment by Joechengli** [comment]
version : v1.101.0-cluster

**Comment by jiekun** [comment]
Hi @Joechengli Thank you for your issue report. 
I'm curious about this one. May I ask what (filter) expression or arguments you use with `vmstorage`? It would be nice if you can describe the detailed steps to reproduce it.

**Comment by makasim** [comment]
Closing due to lack of additional information. Please reopen if more details become available.
