### ISSUE TITLE
Bad input to vmui can cause Victoria Metrics to panic

### ISSUE THREAD

**Issue by shric** [VictoriaMetrics/VictoriaMetrics#6736]
### Describe the bug

I discovered, by accident, certain classes of queries in vmui cause a panic of Victoria Metrics when I click the "prettify query" button. 

### To Reproduce

1. Enter a certain query into vmui.
2. Click "prettify query".

I do not know if it is irresponsible to state the query here because I believe it can be used to cause any Victoria Metrics to panic if you can reach vmui. I assume most/all vmui's are not publicly accessible, but better safe than sorry.

If and when someone involved with Victoria Metrics replies to this and tells me to either paste the query here or send an email somewhere or whatever, I will give the query.

### Version

```
$ ./victoria-metrics-prod --version
victoria-metrics-20240717-185111-tags-v1.102.0-0-g65bb429b81
```
I have also tried older versions.

### Logs

```
2024-07-31T10:45:31.669Z	info	VictoriaMetrics/app/victoria-metrics/main.go:84	started VictoriaMetrics in 0.025 seconds
2024-07-31T10:45:31.669Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:121	starting server at http://127.0.0.1:8428/
2024-07-31T10:45:31.669Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:122	pprof handlers are exposed at http://127.0.0.1:8428/debug/pprof/
panic: BUG: duration "BAR" must be already parsed with expandWithExpr()

goroutine 274 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:293 +0x5b
panic({0xb2ff00?, 0xc0005003b0?})
	runtime/panic.go:770 +0x132
github.com/VictoriaMetrics/metricsql.(*DurationExpr).AppendString(0xc000b12df8?, {0xc0005162c0?, 0xc0005162c0?, 0x1?})
	github.com/VictoriaMetrics/metricsql@v0.76.0/parser.go:1582 +0x11b
github.com/VictoriaMetrics/metricsql.(*RollupExpr).appendModifiers(0xc000513040, {0xc0005162c0?, 0x6?, 0x8?})
	github.com/VictoriaMetrics/metricsql@v0.76.0/parser.go:2103 +0x79
github.com/VictoriaMetrics/metricsql.(*RollupExpr).AppendString(0xc000513040, {0xc0001fc080?, 0x8?, 0x1?})
	github.com/VictoriaMetrics/metricsql@v0.76.0/parser.go:2097 +0x11d
github.com/VictoriaMetrics/metricsql.(*withExpr).AppendString(0xc0006da0c0, {0x0?, 0x0?, 0x5e00002000b12f08?})
	github.com/VictoriaMetrics/metricsql@v0.76.0/parser.go:2019 +0x14f
github.com/VictoriaMetrics/metricsql.appendPrettifiedExpr({0x0?, 0x0, 0x1b?}, {0xe5d5e0, 0xc0006da0c0}, 0x0, 0x0)
	github.com/VictoriaMetrics/metricsql@v0.76.0/prettifier.go:27 +0x138
github.com/VictoriaMetrics/metricsql.Prettify({0xc000195230?, 0xc000b08090?})
	github.com/VictoriaMetrics/metricsql@v0.76.0/prettifier.go:10 +0x45
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.PrettifyQuery({0xe5f9e0, 0xc000b08090}, 0xc0001eaa20)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus/prometheus.go:95 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect.handleStaticAndSimpleRequests({0xe5f9e0, 0xc000b08090}, 0xc0001eaa20, {0xc00024ebdf, 0xf})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/main.go:519 +0x768
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect.RequestHandler({0xe5f9e0, 0xc000b08090}, 0xc0001eaa20)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/main.go:110 +0x14e
main.requestHandler({0xe5f9e0, 0xc000b08090}, 0xc0001eaa20)
	github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc00019cac0, {0xe5ffb0, 0xc0001a5400}, 0xc0001eaa20, 0xda0530)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:418 +0xf51
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xe5ffb0?, 0xc0001a5400?}, 0x0?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:252 +0x31
net/http.HandlerFunc.ServeHTTP(0x1428000?, {0xe5ffb0?, 0xc0001a5400?}, 0x4?)
	net/http/server.go:2171 +0x29
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0xe5f830, 0xc000b380e0}, 0xc0001eaa20)
	github.com/klauspost/compress@v1.17.9/gzhttp/compress.go:495 +0x54f
net/http.HandlerFunc.ServeHTTP(0x46e0b9?, {0xe5f830?, 0xc000b380e0?}, 0xc000b13b68?)
	net/http/server.go:2171 +0x29
net/http.serverHandler.ServeHTTP({0xc00069da40?}, {0xe5f830?, 0xc000b380e0?}, 0x6?)
	net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00096e120, {0xe60638, 0xc00069d800})
	net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 269
	net/http/server.go:3290 +0x4b4
```

### Screenshots

N/A

### Used command-line flags

I believe flags are irrelevant, can download a release and:
```
./victoria-metrics-prod 
```

**Comment by hagen1778** [comment]
Hi @shric! It would be nice if you could send the query to solutionengineering@victoriametrics.com.

**Comment by shric** [comment]
I have now sent the email

**Comment by jiekun** [comment]
FYI,  this bug should be fixed in [v1.102.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.1).

**Comment by hagen1778** [comment]
Closing this ticket as fixed. Thanks for reporting @shric and feel free to reopen if you still observe issues in the [v1.102.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.1) release.

**Comment by shric** [comment]
Thank you for the extremely fast fix and release!
