### ISSUE TITLE
Deleting a pvc casued vmstorage pod panic and it keeps crashing with a "FATAL: cannot sync file" error

### ISSUE THREAD

**Issue by deng47** [VictoriaMetrics/VictoriaMetrics#6745]
### Describe the bug

I manage an 8-node vmcluster(v1.95.1-cluster) with operator:v0.45.0 and I tried to upgrade it to v1.102.1-cluster. All pods were updated successfully except one last vmstorage pod. It kept crashing due to a fatal input/output error
```
2024-08-01T17:39:40.157Z	panic	VictoriaMetrics/lib/storage/storage.go:971	FATAL: cannot read /vm-data/cache/curr_hour_metric_ids: read /vm-data/cache/curr_hour_metric_ids: input/output error
panic: FATAL: cannot read /vm-data/cache/curr_hour_metric_ids: read /vm-data/cache/curr_hour_metric_ids: input/output error
```
I suspected the pvc of that vmstorage pod was corrupted, so I deleted the pvc and restarted the vmstorage pod. The vmstorage pod recreated a new pvc successfully, but still keeps crashing due to  `FATAL: cannot sync file` errors with different file names in either the indexdb dir or data/small dir. Removing those dirs or deleting the pvc doesn't help.
```
2024-08-01T19:35:19.687Z	panic	VictoriaMetrics/lib/filestream/filestream.go:245	FATAL: cannot sync file "/vm-data/indexdb/17E7B119358B9491/17E7B1D4985408BB/index.bin": &{%!d(string=sync) %!d(string=/vm-data/indexdb/17E7B119358B9491/17E7B1D4985408BB/index.bin) 5}
panic: FATAL: cannot sync file "/vm-data/indexdb/17E7B119358B9491/17E7B1D4985408BB/index.bin": &{%!d(string=sync) %!d(string=/vm-data/indexdb/17E7B119358B9491/17E7B1D4985408BB/index.bin) 5}

goroutine 1126 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x90f1b3, 0x5}, {0xc0002b2240, 0xb6}, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:301 +0xa74
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x90f1b3, 0x5}, {0x91c463?, 0xc00088e170?}, {0xc003ee1b28?, 0x6c43c5?, 0xc0005ed5c0?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:141 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:133
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:129
github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream.(*Writer).MustClose(0xc0005ed620)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream/filestream.go:245 +0x1f8
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamWriter).MustClose(0xc0006fed80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/block_stream_writer.go:120 +0xcd
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mergeBlockStreams(0xc005bebe80, 0xc0006fed80, {0xc0001be2e0, 0x4, 0x4}, 0x9ba808, 0x0, 0xc00017e3e8)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:39 +0x19f
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergePartsInternal(0xc00017e3c0, {0xc0005f4640, 0x32}, 0xc0006fed80, {0xc0001be2e0, 0x4, 0x4}, 0x1, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:1328 +0x17a
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc00017e3c0, {0xc0001be260, 0x4, 0x4}, 0x0, 0x1)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:1227 +0x58c
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeInmemoryPartsToFiles.func1({0xc0001be260?, 0x0?, 0xc00017e3c0?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:702 +0x7f
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeInmemoryPartsToFiles in goroutine 86
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:696 +0xde
```

### To Reproduce

delete the pvc of a vmstorage pod

### Version

v1.102.1-cluster

### Logs

root@node4:~/shasta-monitoring/victoriametrics# kubectl logs -n vm vmstorage-7 -f
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmstorage-20240801-130145-tags-v1.102.1-cluster-0-g115a76d28c
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="1ms"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":8482"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="12"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="10000000000"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/vm-data"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -vminsertAddr=":8400"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -vmselectAddr=":8401"
2024-08-01T21:21:55.898Z	info	VictoriaMetrics/app/vmstorage/main.go:102	opening storage at "/vm-data" with -retentionPeriod=12
2024-08-01T21:21:55.899Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 10307921510 bytes, leaving 6871947674 bytes to the OS according to -memory.allowedPercent=60
2024-08-01T21:21:56.113Z	info	VictoriaMetrics/lib/mergeset/table.go:1513	deleting "/vm-data/indexdb/17E7B58FB6196A65/17E7B75D2CA08BDD" because it isn't listed in "/vm-data/indexdb/17E7B58FB6196A65/parts.json"; this is the expected case after unclean shutdown
2024-08-01T21:21:56.216Z	info	VictoriaMetrics/app/vmstorage/main.go:114	successfully opened storage "/vm-data" in 0.318 seconds; partsCount: 1; blocksCount: 64006; rowsCount: 64006; sizeBytes: 518406
2024-08-01T21:21:56.217Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:74	accepting vminsert conns at 0.0.0.0:8400
2024-08-01T21:21:56.217Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:121	starting server at http://127.0.0.1:8482/
2024-08-01T21:21:56.217Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:122	pprof handlers are exposed at http://127.0.0.1:8482/debug/pprof/
2024-08-01T21:21:56.217Z	info	VictoriaMetrics/lib/vmselectapi/server.go:158	accepting vmselect conns at 0.0.0.0:8401
2024-08-01T21:21:57.675Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:123	processing vminsert conn from 10.42.28.110:59216
2024-08-01T21:21:57.725Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:123	processing vminsert conn from 10.42.30.210:37356
2024-08-01T21:21:57.741Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:123	processing vminsert conn from 10.42.20.237:34174
2024-08-01T21:21:57.823Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:123	processing vminsert conn from 10.42.0.163:35056
2024-08-01T21:21:57.837Z	info	VictoriaMetrics/app/vmstorage/servers/vminsert.go:123	processing vminsert conn from 10.42.17.142:50752
2024-08-01T21:22:06.362Z	panic	VictoriaMetrics/lib/filestream/filestream.go:245	FATAL: cannot sync file "/vm-data/data/small/2024_08/17E7B7A85BD75B87/index.bin": &{%!d(string=sync) %!d(string=/vm-data/data/small/2024_08/17E7B7A85BD75B87/index.bin) 5}
panic: FATAL: cannot sync file "/vm-data/data/small/2024_08/17E7B7A85BD75B87/index.bin": &{%!d(string=sync) %!d(string=/vm-data/data/small/2024_08/17E7B7A85BD75B87/index.bin) 5}

goroutine 966 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x90f1b3, 0x5}, {0xc00014c370, 0xaa}, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:301 +0xa74
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x90f1b3, 0x5}, {0x91c463?, 0xc002f024e0?}, {0xc013c55b20?, 0x6c43c5?, 0xc000371710?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:141 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:133
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:129
github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream.(*Writer).MustClose(0xc0003716b0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream/filestream.go:245 +0x1f8
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*blockStreamWriter).MustClose(0xc0081e4480)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/block_stream_writer.go:127 +0xe3
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mergeBlockStreams(0xc002fc6b10, 0xc0081e4480, {0xc0001240c0, 0x1, 0x1}, 0x0, 0xc0001d01c0, 0x18994149d43, 0xc0002f3838, 0xc0002f3850)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/merge.go:26 +0x1bf
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergePartsInternal(0xc0002f3800, {0xc01581a030, 0x2c}, 0xc0081e4480, {0xc0001240c0, 0x1, 0x1}, 0x1, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1565 +0x245
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc0002f3800, {0xc000124008, 0x1, 0x1}, 0x0, 0x1)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1426 +0x5dc
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergePartsToFiles.func1({0xc000124008?, 0x2492492492492492?, 0xc0002f3800?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1183 +0x93
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergePartsToFiles in goroutine 96
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1177 +0xef

**Comment by deng47** [comment]
I think I found the cause. My node has a bad fs. Sorry for all the troubles.
# dmesg | tail
[3144734.550020] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928884, rd 102999, flush 0, corrupt 0, gen 0
[3144734.561818] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928885, rd 102999, flush 0, corrupt 0, gen 0
[3144734.573537] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928886, rd 102999, flush 0, corrupt 0, gen 0
[3144734.584967] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928887, rd 102999, flush 0, corrupt 0, gen 0
[3144734.596651] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928888, rd 102999, flush 0, corrupt 0, gen 0
[3144734.607992] BTRFS error (device nvme1n1p1): bdev /dev/nvme3n1p1 errs: wr 928889, rd 102999, flush 0, corrupt 0, gen 0
[3144734.619921] BTRFS warning (device nvme1n1p1): lost page write due to IO error on /dev/nvme3n1p1 (-5)
[3144734.619934] BTRFS warning (device nvme1n1p1): lost page write due to IO error on /dev/nvme3n1p1 (-5)
[3144734.619940] BTRFS warning (device nvme1n1p1): lost page write due to IO error on /dev/nvme3n1p1 (-5)
[3144734.619996] BTRFS error (device nvme1n1p1): error writing primary super block to device 3
