### ISSUE TITLE
vmstorage: improve cache usage for retention and downsampling filters

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#7182]
### Is your feature request related to a problem? Please describe

Currently, a background merge with `retentionFilters` or downsampling filters enabled can significantly increase memory usage and lead OOM issues.

Both retention and downsampling filters need are using [`IndexSearch.searchMetricNameWithCache`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ed5da38ede1f67b0eabcd04ca83dda8c4bb874fa/lib/storage/index_db.go#L1908-L1922) API to find a metric name.  This API uses a cache for inmemory blocks when accessing different blocks: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e84c87750357a289a280acc59a93b44d9d57d646/lib/mergeset/part_search.go#L306-L314

In case of downsampling and retention there can be a lot of metricIDs to check within a short period of time. This can lead to quick and uncontrollable growth of the cache size and lead to OOM errors.

### Describe the solution you'd like

It would be great to add an option to skip caching for some types of searches for [`partSearch.getInmemoryBlock`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e84c87750357a289a280acc59a93b44d9d57d646/lib/mergeset/part_search.go#L301) so that it will be possible to avoid cache poisoning for use-cases when it is expected to scan a large number of entries on purpose.

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7269 has been merged and will likely be included into the next release.

**Comment by zekker6** [comment]
Commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/8198e7241d05bdea21527ab261fd9c37ca530fb6 have been reverted and will not be included in [v1.106.0](https://docs.victoriametrics.com/changelog/#v11060) as it is not yet fully tested.
We'll work on more extensive testing and re-applying in the next releases.

**Comment by valyala** [comment]
@zekker6 , the following test fails after the commit https://github.com/VictoriaMetrics/VictoriaMetrics-enterprise/commit/aa6f89be71dc32ff159780037cab13035a109f96 in the `VictoriaMetrics-enterprise` repository:

```
--- FAIL: TestIndexDB (0.03s)
    --- FAIL: TestIndexDB/serial (0.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64f3c0]

goroutine 1296 [running]:
testing.tRunner.func1.2({0x80bba0, 0xb5de40})
	/home/valyala/work/go/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/home/valyala/work/go/src/testing/testing.go:1635 +0x35e
panic({0x80bba0?, 0xb5de40?})
	/home/valyala/work/go/src/runtime/panic.go:785 +0x132
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).getIndexSearchInternal(0x0, 0xffffffffffffffff, 0x0)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db.go:535 +0x20
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).searchMetricName.func1(0xc012188480)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db.go:1556 +0x4d
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).doExtDB(0xc0121883c0?, 0xc0001c1958)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db.go:286 +0xaa
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).searchMetricName(0xc0121883c0, {0x0, 0x0, 0x0}, 0x1, 0x0)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db.go:1555 +0x1cf
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.testIndexDBCheckTSIDByName(0xc0121883c0, {0xc0141c4008, 0x191, 0x0?}, {0xc0141a4000, 0x191, 0x605?}, 0x0)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db_test.go:741 +0x455
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.TestIndexDB.func1(0xc0120229c0)
	/home/valyala/work/VictoriaMetrics/lib/storage/index_db_test.go:591 +0x10f
testing.tRunner(0xc0120229c0, 0x9034c0)
	/home/valyala/work/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1295
	/home/valyala/work/go/src/testing/testing.go:1743 +0x390
FAIL	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage	1.235s
FAIL
```

**Comment by hagen1778** [comment]
@valyala the problem was addressed and tests are passing now. Thanks for noticing!

**Comment by zekker6** [comment]
This improvement was included in release [v1.109.0](https://docs.victoriametrics.com/changelog/#v11090).
