### ISSUE TITLE
BUG: NewChild() cannot be called after Donef(%q) call

### ISSUE THREAD

**Issue by lookshun** [VictoriaMetrics/VictoriaMetrics#7265]
### Describe the bug

`BUG: NewChild() cannot be called after Donef(%q) call` occurs when vmselect is running in production. 
It seems like that the error occurs when storage returns data.
No other changes such as `CI/CD`.

### To Reproduce

![image](https://github.com/user-attachments/assets/73dfc9f3-7a36-4c66-a1b4-a241a7aa70d6)

if you need any info else. let me known. thank you.

### Version

> **vmselect and vmstorage is not the same version.**

vmselect: `vmselect-20240116-223959-tags-v1.87.13-cluster-0-gb0c9bc990`
vmstorage: `vmstorage-20230620-062512-v1.87.6-cluster-0-g468cd5f`

### Logs

as the screenshot shows.

**Comment by hagen1778** [comment]
Hello @lookshun! 

> vmselect: vmselect-20240116-223959-tags-v1.87.13-cluster-0-gb0c9bc990
vmstorage: vmstorage-20230620-062512-v1.87.6-cluster-0-g468cd5f

These are pretty old versions. I'd recommend following https://docs.victoriametrics.com/troubleshooting/#general-troubleshooting-checklist and updating to the newer versions of VM. There is no way we can deliver fix to old version of VM.

**Comment by lookshun** [comment]
Okey, I will update, Thank you very much.

**Comment by jiekun** [comment]
Could be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5319. Please also check the fix commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0730c2586dd33227e99250cfeb9ea5ddb110e638 which is available since [v1.95.0-cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.95.0-cluster).

@lookshun Please comment if you tried the newer version (at least >= 1.95.0, we recommend newer version which include a lot of bug fix), so that we could label or close this issue properly.

**Comment by hagen1778** [comment]
@lookshun I'm closing this issue. Feel free to re-open or create a new one if panic still occurs.

**Comment by lcasi** [comment]
I have found the same problem with version v1.97.1:
```shell 
panic: BUG: NewChild() cannot be called after Donef("rpc at <xxx>.svc.cluster.local:8401: cancel request because of error in other vmstorage nodes") call

goroutine 4402346 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer.(*Tracer).NewChild(0xa9a9a9?, {0xa96846?, 0x10?}, {0xc000869e00?, 0xa6e260?, 0xc000869d90?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/querytracer/tracer.go:81 +0x1d7
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).execOnConnWithPossibleRetry(0x2c?, 0xc000869f50?, {0xa9a9a9, 0x14}, 0xc000869e70?, {0x67633a67, 0x6fc23ac00, {0xa9d9b0, 0x18}})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:2238 +0xcb
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*storageNode).processSearchMetricNames(0xc000869f50?, 0x2?, {0xc015ecc200?, 0x0?, 0x0?}, {0x3?, 0x1640?, {0xa9d9b0?, 0x0?}})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:2223 +0x94
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.SearchMetricNames.func1(0xc000e3ced8?, 0xc000869fb8?, 0xc00012e410)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1612 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest.func1(0x7597e7?, 0xc00012e410)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1817 +0x3a
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.startStorageNodesRequest in goroutine 4397472
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1816 +0x7b
```

**Comment by hagen1778** [comment]
Hello @lcasi! It is likely related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8114 and should be addressed in the upcomming release.

**Comment by lcasi** [comment]
> Hello [@lcasi](https://github.com/lcasi)! It is likely related to [#8114](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8114) and should be addressed in the upcomming release.

ok, Thank you. I'll try upgrade it to verify
