### ISSUE TITLE
Unrecoverable error when merging big parts in the partition

### ISSUE THREAD

**Issue by foxdalas** [VictoriaMetrics/VictoriaMetrics#76]
`2019-06-23T20:07:13.563+0000	panic	lib/storage/partition.go:753	FATAL: unrecoverable error when merging big parts in the partition "/victoria-metrics-data/data/big/2019_06": error when merging parts to "/victoria-metrics-data/data/big/2019_06/tmp/15AAEC98CB9B95F8": cannot merge 3 streams: cannot unmarshal and calibrate scale for blocks to be merged: cannot unmarshal 2192 values from len(src)=2225 bytes: cannot decompress zstd data of size 2225: decompression error: Corrupted block detected
panic: FATAL: unrecoverable error when merging big parts in the partition "/victoria-metrics-data/data/big/2019_06": error when merging parts to "/victoria-metrics-data/data/big/2019_06/tmp/15AAEC98CB9B95F8": cannot merge 3 streams: cannot unmarshal and calibrate scale for blocks to be merged: cannot unmarshal 2192 values from len(src)=2225 bytes: cannot decompress zstd data of size 2225: decompression error: Corrupted block detected

goroutine 71 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xaa0b6b, 0x5, 0xc1140b8e00, 0x1ae, 0x3)
	/VictoriaMetrics/lib/logger/logger.go:124 +0x53d
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(0xaa0b6b, 0x5, 0xac4c41, 0x49, 0xc003da3f88, 0x2, 0x2)
	/VictoriaMetrics/lib/logger/logger.go:78 +0x113
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	/VictoriaMetrics/lib/logger/logger.go:62
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).bigPartsMerger(0xc0000e62c0)
	/VictoriaMetrics/lib/storage/partition.go:753 +0x127
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func2(0xc0000e62c0)
	/VictoriaMetrics/lib/storage/partition.go:745 +0x2b
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	/VictoriaMetrics/lib/storage/partition.go:744 +0xc8`

After delete tmp dir working fine 3+ hours

**Comment by valyala** [comment]
> decompression error: Corrupted block detected

This looks like disk corruption. Could you check disk for errors? What type of disk do you use?

The workaround is to delete the corrupted parts. The error message doesn't mention path to corrupted part - it just mentions path to the destination part. This should be fixed in the next version.

**Comment by valyala** [comment]
Added a section to README.md with the description on how to recover from corrupted parts due to disk errors: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#troubleshooting

**Comment by valyala** [comment]
VictoriaMetrics [v1.20.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) should show the filesystem path to broken parts during merge error. This should help in determining broken parts.

**Comment by valyala** [comment]
@foxdalas , I'm going to close this issue, since it is likely it is related to corrupted disk. Upgrade to v1.20.5 or newer version and re-open the issue again if you'll see this error again. Make sure you checked disk for errors before re-opening the issue.

VictoriaMetrics cannot recover from disk errors. There are plans for creating `vmrecover` tool, which could recover as much data as possible from corrupted parts. Currently the easiest solution is to delete the corrupted part.

**Comment by tekert** [comment]
Sorry to revive this, but at the second day of testing vivtoria metrics, the lights when out, and when they came back i noticed the service was not starting due to error (in the future if this happens it would be good to try an auto-recover if possible)

```
2023-06-25T11:53:40.785Z	panic	VictoriaMetrics/lib/storage/partition.go:1098	FATAL: unrecoverable error when merging parts in the partition ("C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06", "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_06"): cannot merge 15 parts to C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE4C3F6E0735D: cannot merge 15 streams: [C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F58 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC15 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC19 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC17 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3B3BA7AE1B1 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3ACCAEB5415 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F57 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3ACCAEB5417 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F59 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F56 partHeader{rowsCount=1136,blocksCount=1136,minTimestamp=1687694019871,maxTimestamp=1687694019983} C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC1A C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC18 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC16 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC14]: cannot read block to be merged: cannot obtain the next block to merge: error when reading part "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06\\176BC51DC042DC15": cannot read next block: cannot read index block: cannot decompress index block at offset 0: cannot decompress zstd block with len=2671 to a buffer with len=0: invalid input: magic number mismatch; block data (hex): 494E4458280009005701389E3D00000000000000000000002800000038000000E80F0000000000000200000000791116C1286645000000000000000000000000000000000000000010000000020000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000200100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E000000000000000000000010000000020000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E00000000000000000000001000000002000000E4000001B655DE05E500E6E8E97777B945D7C7460A2E000003942F00000396778D9CE8FC0E8BB3B87800000098AC79037A00107002810543200082025B800200C612D680C3CC8AB9040000000052054C080802090A0B060060073E7D9722F561A4E6AD3A0C61C000390A8C60007FADE63B889AA77FB7E70000012EEA001EEB04B7E800000B08E90102EC002289E8C65C37592B73B865022326E8D778176667260FF86EBC696A6B2ECB2734866C6D6EB868028BED00A5BC170303409382BD3BDCC3C9B896174A53BB4922A6D631A6C25478FCB90C00000000000C020D0AACA3BBA2F82E3B75BA23017600BA24B58D9F5C140610CE2B00001C2CBDDB2402E6CD9447AB000000000046ACAF4CB054B10802C51DB96A2E6F46007076B8A90602AA3800030340BFB44AB091292551F41AEE47105A17F500F6F10528ECB98F5E1BF200F3C20BEB733DBF78287B00000000667D2E4A03030340C94F26B44D03C21EBA000204BB02BC0E00BD0204BE02BF0000030340D2055B6CA021048B344835363742434445DA57F8108A35F9E07E00DB294DE44CAD04C1B91D04802F88BCC8171E039BC7651EB81F02EA210CE404201F19CD25F8220382667D9B602305F2B66729A21B24252602F447CDB68E17B91302794CA2AFC214076BE5F2F93E1705E877CA2C7C18F75E7EA720191AD99115B1D81B02D2B4D2A5A01C21E4E6774F579CF522B9011550851390110201082C2A8600130000F167AA2DEE03171DE16D2011030340E8701062900A91EB1019A2085EB31813110F99EB1A4120150170EBFB4D8E0200000E2E821CB5D4AE0F0012E9021AD81B8CB00FB8800000000001160C83032AF29F73E03FD09A5EFA08A8A7FD074F0C00FE0C19F540FF0FDDBE00B8F8034F8BF90000E99006FB03FF34E000FCF0B0A0F87F777E5B7E4B014D0000FA56EA0B4E02A77E32FDAC264B9DD8024C6F0555B095A67E177006A9A9E9A4DA710557316A1DD0726D2BDC837E737E09B74534745C68F35D607504FA89822B9E76050ED40090527700E4B73FF45413030340FF58E1BC3A60DB67BA3100BA3200000003034082D8A872D93142CC1B0B847B01920E00A234C50112A0000C0001308E2160308061498A8128821A0220004001000008181E7ABA53612E14823FA147B2DD81D9F86CE62EC8B81CB172A39CD8F69272D3CC7B3E14840B19F11EA2B8BBB0D44AE910EA94A8A17024F24C3BA50E1FBF5069F38D9F1184F9532DAD0261795728A591F0742C3F8C2C05A580DABF281BD80DF3C1CF5ABA55F7C20DE27F31A6C26C6A4641F1C87EB60DBB5496118C5F4BFDE42823265CA7C546D40038A2A3D3CAA95A5308661F07950A2ACD425EA2E6FC20E6370637C3BA7501F6B647590FAB24559E995196D07EFEE4B977934D3B69D2A408E65E6C4B80E548D733A416060DFAECD3A7A83F1BD2F5CB5CC60293F4BC036AAFBC713A8292BF4A9FE75952322BB570EB383794A23AF1754E8BD62C9B0E789AC7693297C05A8E29E299870EC8CB34545D8702008C83017C2923E1687A16331859D27E5F2553A58A2B7698B86839AC3848D6FCBE421BD1A2A3A0DBC3EFD625F5465FA44AF0DC5E44DE242FA1905251B0A49C5C3D7243D95AA334500696A95CE43C171BA60812EB50C258C0FA3CA378471D2F3D46F51C4AD2B4F9DC53C9EC15F57443DDAA73E9C55267EA4896A2272995D9E6ED491D54436FBA16352D25548CC24C641FE3D2BEEFBAE713E2226C5541B1D4FEF21B1D89848E3AEE78E1C2F9BF198C52F4BE0E2D0155054A74B8AECF8C6018838D4ABEA144879147F2EC68805B0AD8EBED2DC505D97A7A7C0C05D93A0E5CDF1DAE6694C5EA086DDA68309ED15E88F9CA8E228652273A0D2DCE4AF242A4E0EC9200AD405B81B682AB0A04BA07DC4FF61B6B85A5C64F6E1ABBB8DAF6EDFAF6DBA76FDFFDF6E9B76A8287B37DEACCE8D56900902250CEAC3E5C64BDDB416F5222E24D044A238383D89A8EBB293E4964507519FFD8C1998BF71ADC9A8C48CD178A717F275208DE1D8DD53B577557B52E75AEB65CEA4E6D9DD45DD5BAA4BBB20523C9BFD9B451C276EA1FAD3725E7148B077E4B5F2475E527816DD3CEC962C092ACA69EF8989A5E192D38F8C5A2E12BD9A4D8327310CF32429950A3FD8F0AB699570B9B9ED9247569C2B898F552BEC5FF797E268E045182B134F0C152A69C4D4EEE5D2AB430BEB75B296B0435168585EF077AD88D38D2653EAD5BB794F92E3592458902004DBF89840E1D7BECA0630F5DC15576FD1A2A49335E6C282DB653A616862AA67B14219900F3B5AC9DD4809449CA9865015030914C03AB6DFD12B43A4F7077756A3D659D8ED31D126D6F9B920A9052EFAEB75364B337E3F2476AC6DEEC95460F45EEE3EF07966F2AF91EFF126264BF3F
panic: FATAL: unrecoverable error when merging parts in the partition ("C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06", "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\big\\2023_06"): cannot merge 15 parts to C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE4C3F6E0735D: cannot merge 15 streams: [C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F58 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC15 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC19 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC17 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3B3BA7AE1B1 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3ACCAEB5415 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F57 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3ACCAEB5417 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F59 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BE3A2C6388F56 partHeader{rowsCount=1136,blocksCount=1136,minTimestamp=1687694019871,maxTimestamp=1687694019983} C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC1A C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC18 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC16 C:\Monitoring\victoria-metrics\victoria-metrics-data\data\small\2023_06\176BC51DC042DC14]: cannot read block to be merged: cannot obtain the next block to merge: error when reading part "C:\\Monitoring\\victoria-metrics\\victoria-metrics-data\\data\\small\\2023_06\\176BC51DC042DC15": cannot read next block: cannot read index block: cannot decompress index block at offset 0: cannot decompress zstd block with len=2671 to a buffer with len=0: invalid input: magic number mismatch; block data (hex): 494E4458280009005701389E3D00000000000000000000002800000038000000E80F0000000000000200000000791116C1286645000000000000000000000000000000000000000010000000020000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000200100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E0000000000000000000000100000000200000068005600000000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E000000000000000000000010000000020000000F1903000000A702DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D901DEDEAA6E56A7D9010000000000000000000000000000000020000000000000000A03760061006C007500650073002E00620069006E00000000000000000000001000000002000000E4000001B655DE05E500E6E8E97777B945D7C7460A2E000003942F00000396778D9CE8FC0E8BB3B87800000098AC79037A00107002810543200082025B800200C612D680C3CC8AB9040000000052054C080802090A0B060060073E7D9722F561A4E6AD3A0C61C000390A8C60007FADE63B889AA77FB7E70000012EEA001EEB04B7E800000B08E90102EC002289E8C65C37592B73B865022326E8D778176667260FF86EBC696A6B2ECB2734866C6D6EB868028BED00A5BC170303409382BD3BDCC3C9B896174A53BB4922A6D631A6C25478FCB90C00000000000C020D0AACA3BBA2F82E3B75BA23017600BA24B58D9F5C140610CE2B00001C2CBDDB2402E6CD9447AB000000000046ACAF4CB054B10802C51DB96A2E6F46007076B8A90602AA3800030340BFB44AB091292551F41AEE47105A17F500F6F10528ECB98F5E1BF200F3C20BEB733DBF78287B00000000667D2E4A03030340C94F26B44D03C21EBA000204BB02BC0E00BD0204BE02BF0000030340D2055B6CA021048B344835363742434445DA57F8108A35F9E07E00DB294DE44CAD04C1B91D04802F88BCC8171E039BC7651EB81F02EA210CE404201F19CD25F8220382667D9B602305F2B66729A21B24252602F447CDB68E17B91302794CA2AFC214076BE5F2F93E1705E877CA2C7C18F75E7EA720191AD99115B1D81B02D2B4D2A5A01C21E4E6774F579CF522B9011550851390110201082C2A8600130000F167AA2DEE03171DE16D2011030340E8701062900A91EB1019A2085EB31813110F99EB1A4120150170EBFB4D8E0200000E2E821CB5D4AE0F0012E9021AD81B8CB00FB8800000000001160C83032AF29F73E03FD09A5EFA08A8A7FD074F0C00FE0C19F540FF0FDDBE00B8F8034F8BF90000E99006FB03FF34E000FCF0B0A0F87F777E5B7E4B014D0000FA56EA0B4E02A77E32FDAC264B9DD8024C6F0555B095A67E177006A9A9E9A4DA710557316A1DD0726D2BDC837E737E09B74534745C68F35D607504FA89822B9E76050ED40090527700E4B73FF45413030340FF58E1BC3A60DB67BA3100BA3200000003034082D8A872D93142CC1B0B847B01920E00A234C50112A0000C0001308E2160308061498A8128821A0220004001000008181E7ABA53612E14823FA147B2DD81D9F86CE62EC8B81CB172A39CD8F69272D3CC7B3E14840B19F11EA2B8BBB0D44AE910EA94A8A17024F24C3BA50E1FBF5069F38D9F1184F9532DAD0261795728A591F0742C3F8C2C05A580DABF281BD80DF3C1CF5ABA55F7C20DE27F31A6C26C6A4641F1C87EB60DBB5496118C5F4BFDE42823265CA7C546D40038A2A3D3CAA95A5308661F07950A2ACD425EA2E6FC20E6370637C3BA7501F6B647590FAB24559E995196D07EFEE4B977934D3B69D2A408E65E6C4B80E548D733A416060DFAECD3A7A83F1BD2F5CB5CC60293F4BC036AAFBC713A8292BF4A9FE75952322BB570EB383794A23AF1754E8BD62C9B0E789AC7693297C05A8E29E299870EC8CB34545D8702008C83017C2923E1687A16331859D27E5F2553A58A2B7698B86839AC3848D6FCBE421BD1A2A3A0DBC3EFD625F5465FA44AF0DC5E44DE242FA1905251B0A49C5C3D7243D95AA334500696A95CE43C171BA60812EB50C258C0FA3CA378471D2F3D46F51C4AD2B4F9DC53C9EC15F57443DDAA73E9C55267EA4896A2272995D9E6ED491D54436FBA16352D25548CC24C641FE3D2BEEFBAE713E2226C5541B1D4FEF21B1D89848E3AEE78E1C2F9BF198C52F4BE0E2D0155054A74B8AECF8C6018838D4ABEA144879147F2EC68805B0AD8EBED2DC505D97A7A7C0C05D93A0E5CDF1DAE6694C5EA086DDA68309ED15E88F9CA8E228652273A0D2DCE4AF242A4E0EC9200AD405B81B682AB0A04BA07DC4FF61B6B85A5C64F6E1ABBB8DAF6EDFAF6DBA76FDFFDF6E9B76A8287B37DEACCE8D56900902250CEAC3E5C64BDDB416F5222E24D044A238383D89A8EBB293E4964507519FFD8C1998BF71ADC9A8C48CD178A717F275208DE1D8DD53B577557B52E75AEB65CEA4E6D9DD45DD5BAA4BBB20523C9BFD9B451C276EA1FAD3725E7148B077E4B5F2475E527816DD3CEC962C092ACA69EF8989A5E192D38F8C5A2E12BD9A4D8327310CF32429950A3FD8F0AB699570B9B9ED9247569C2B898F552BEC5FF797E268E045182B134F0C152A69C4D4EEE5D2AB430BEB75B296B0435168585EF077AD88D38D2653EAD5BB794F92E3592458902004DBF89840E1D7BECA0630F5DC15576FD1A2A49335E6C282DB653A616862AA67B14219900F3B5AC9DD4809449CA9865015030914C03AB6DFD12B43A4F7077756A3D659D8ED31D126D6F9B920A9052EFAEB75364B337E3F2476AC6DEEC95460F45EEE3EF07966F2AF91EFF126264BF3F

goroutine 106 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x151daa1, 0x5}, {0xc002d32000, 0x1d27}, 0x3?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x151daa1, 0x5}, {0x155c14a?, 0x0?}, {0xc002d4bf78?, 0x0?, 0x0?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc00012a180)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1098 +0x1ea
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1071 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1070 +0x27```

**Comment by tekert** [comment]
Well, i resolved it after 2 hours:

Steps:
1.- Delete FILE in "error when reading part : <FILE>"
2.- Delete FILE name from parts.json (important to get list of merge errors and not of missing files)
3.- Start service and error will output a new "error when reading part : <FILE2>"
4.- Repeat from step 1 until all errors are gone.
